// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The AlertPolicyService API is used to manage (list, create, delete,
/// edit) alert policies in Cloud Monitoring. An alerting policy is
/// a description of the conditions under which some aspect of your
/// system is considered to be "unhealthy" and the ways to notify
/// people or services about this state. In addition to using this API, alert
/// policies can also be managed through
/// [Cloud Monitoring](https://cloud.google.com/monitoring/docs/),
/// which can be reached by clicking the "Monitoring" tab in
/// [Cloud console](https://console.cloud.google.com/).
///
/// @Snippet(path: "AlertPolicyServiceQuickstart")
public final class AlertPolicyServiceClient: Clients.AlertPolicyServiceProtocol, Sendable {
  let inner: any Clients.AlertPolicyServiceStub

  /// Creates a new `AlertPolicyServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AlertPolicyServiceStub = try Clients.AlertPolicyServiceTransport(options)
    inner = Clients.AlertPolicyServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AlertPolicyServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the existing alerting policies for the workspace.
  ///
  /// @Snippet(path: "AlertPolicyService_ListAlertPolicies")
  public func listAlertPolicies(
    request: ListAlertPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse {
    try await self.inner.listAlertPolicies(request: request, options: options)
  }

  /// Gets a single alerting policy.
  ///
  /// @Snippet(path: "AlertPolicyService_GetAlertPolicy")
  public func getAlertPolicy(
    request: GetAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    try await self.inner.getAlertPolicy(request: request, options: options)
  }

  /// Creates a new alerting policy.
  ///
  /// Design your application to single-thread API calls that modify the state of
  /// alerting policies in a single project. This includes calls to
  /// CreateAlertPolicy, DeleteAlertPolicy and UpdateAlertPolicy.
  ///
  /// @Snippet(path: "AlertPolicyService_CreateAlertPolicy")
  public func createAlertPolicy(
    request: CreateAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    try await self.inner.createAlertPolicy(request: request, options: options)
  }

  /// Deletes an alerting policy.
  ///
  /// Design your application to single-thread API calls that modify the state of
  /// alerting policies in a single project. This includes calls to
  /// CreateAlertPolicy, DeleteAlertPolicy and UpdateAlertPolicy.
  ///
  /// @Snippet(path: "AlertPolicyService_DeleteAlertPolicy")
  public func deleteAlertPolicy(
    request: DeleteAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAlertPolicy(request: request, options: options)
  }

  /// Updates an alerting policy. You can either replace the entire policy with
  /// a new one or replace only certain fields in the current alerting policy by
  /// specifying the fields to be updated via `updateMask`. Returns the
  /// updated alerting policy.
  ///
  /// Design your application to single-thread API calls that modify the state of
  /// alerting policies in a single project. This includes calls to
  /// CreateAlertPolicy, DeleteAlertPolicy and UpdateAlertPolicy.
  ///
  /// @Snippet(path: "AlertPolicyService_UpdateAlertPolicy")
  public func updateAlertPolicy(
    request: UpdateAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    try await self.inner.updateAlertPolicy(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AlertPolicyServiceClient`.
  ///
  /// To mock `AlertPolicyServiceClient` change your functions to receive
  /// `some AlertPolicyServiceProtocol` or `any AlertPolicyServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AlertPolicyServiceProtocol: Sendable {
    /// See `AlertPolicyServiceClient.listAlertPolicies`.
    func listAlertPolicies(
      request: ListAlertPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse

    /// See `AlertPolicyServiceClient.getAlertPolicy`.
    func getAlertPolicy(
      request: GetAlertPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy

    /// See `AlertPolicyServiceClient.createAlertPolicy`.
    func createAlertPolicy(
      request: CreateAlertPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy

    /// See `AlertPolicyServiceClient.deleteAlertPolicy`.
    func deleteAlertPolicy(
      request: DeleteAlertPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AlertPolicyServiceClient.updateAlertPolicy`.
    func updateAlertPolicy(
      request: UpdateAlertPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.AlertPolicy
  }
}

// Default implementations
extension Clients.AlertPolicyServiceProtocol {
  public func listAlertPolicies(request: ListAlertPoliciesRequest) async throws
    -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse
  {
    try await self.listAlertPolicies(request: request, options: .init())
  }

  public func listAlertPolicies(
    request: ListAlertPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAlertPoliciesByItems(
    request: ListAlertPoliciesRequest
  ) -> some AsyncSequence<AlertPolicy, any Swift.Error> & Sendable {
    self.listAlertPoliciesByItems(request: request, options: .init())
  }

  /// Lists the existing alerting policies for the workspace.
  ///
  /// @Snippet(path: "AlertPolicyService_ListAlertPolicies")
  public func listAlertPoliciesByItems(
    request: ListAlertPoliciesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AlertPolicy, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListAlertPoliciesResponse in
      var request = request
      request.pageToken = token
      return try await self.listAlertPolicies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listAlertPoliciesByItems(
    name: Swift.String,
  ) -> some AsyncSequence<AlertPolicy, any Swift.Error> & Sendable {
    let request = ListAlertPoliciesRequest().with {
      $0.name = name
    }
    return self.listAlertPoliciesByItems(request: request)
  }

  public func getAlertPolicy(request: GetAlertPolicyRequest) async throws
    -> GoogleCloudMonitoringV3.AlertPolicy
  {
    try await self.getAlertPolicy(request: request, options: .init())
  }

  public func getAlertPolicy(
    request: GetAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAlertPolicy(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    let request = GetAlertPolicyRequest().with {
      $0.name = name
    }
    return try await self.getAlertPolicy(request: request)
  }

  public func createAlertPolicy(request: CreateAlertPolicyRequest) async throws
    -> GoogleCloudMonitoringV3.AlertPolicy
  {
    try await self.createAlertPolicy(request: request, options: .init())
  }

  public func createAlertPolicy(
    request: CreateAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAlertPolicy(
    name: Swift.String,
    alertPolicy: AlertPolicy?,
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    let request = CreateAlertPolicyRequest().with {
      $0.name = name
      $0.alertPolicy = alertPolicy
    }
    return try await self.createAlertPolicy(request: request)
  }

  public func deleteAlertPolicy(request: DeleteAlertPolicyRequest) async throws {
    try await self.deleteAlertPolicy(request: request, options: .init())
  }

  public func deleteAlertPolicy(
    request: DeleteAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAlertPolicy(
    name: Swift.String,
  ) async throws {
    let request = DeleteAlertPolicyRequest().with {
      $0.name = name
    }
    try await self.deleteAlertPolicy(request: request)
  }

  public func updateAlertPolicy(request: UpdateAlertPolicyRequest) async throws
    -> GoogleCloudMonitoringV3.AlertPolicy
  {
    try await self.updateAlertPolicy(request: request, options: .init())
  }

  public func updateAlertPolicy(
    request: UpdateAlertPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAlertPolicy(
    updateMask: GoogleWKT.WKTFieldMask?,
    alertPolicy: AlertPolicy?,
  ) async throws -> GoogleCloudMonitoringV3.AlertPolicy {
    let request = UpdateAlertPolicyRequest().with {
      $0.updateMask = updateMask
      $0.alertPolicy = alertPolicy
    }
    return try await self.updateAlertPolicy(request: request)
  }
}
