// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Specifies an ordering relationship on two arguments, called `left` and
/// `right`.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ComparisonType: Codable, Equatable, Hashable, Sendable {
  /// No ordering relationship is specified.
  case comparisonUnspecified
  /// True if the left argument is greater than the right argument.
  case comparisonGt
  /// True if the left argument is greater than or equal to the right argument.
  case comparisonGe
  /// True if the left argument is less than the right argument.
  case comparisonLt
  /// True if the left argument is less than or equal to the right argument.
  case comparisonLe
  /// True if the left argument is equal to the right argument.
  case comparisonEq
  /// True if the left argument is not equal to the right argument.
  case comparisonNe
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .comparisonUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .comparisonUnspecified: return 0
    case .comparisonGt: return 1
    case .comparisonGe: return 2
    case .comparisonLt: return 3
    case .comparisonLe: return 4
    case .comparisonEq: return 5
    case .comparisonNe: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .comparisonUnspecified: return "COMPARISON_UNSPECIFIED"
    case .comparisonGt: return "COMPARISON_GT"
    case .comparisonGe: return "COMPARISON_GE"
    case .comparisonLt: return "COMPARISON_LT"
    case .comparisonLe: return "COMPARISON_LE"
    case .comparisonEq: return "COMPARISON_EQ"
    case .comparisonNe: return "COMPARISON_NE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComparisonType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "COMPARISON_UNSPECIFIED": self = .comparisonUnspecified
    case "COMPARISON_GT": self = .comparisonGt
    case "COMPARISON_GE": self = .comparisonGe
    case "COMPARISON_LT": self = .comparisonLt
    case "COMPARISON_LE": self = .comparisonLe
    case "COMPARISON_EQ": self = .comparisonEq
    case "COMPARISON_NE": self = .comparisonNe
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComparisonType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .comparisonUnspecified
    case 1: self = .comparisonGt
    case 2: self = .comparisonGe
    case 3: self = .comparisonLt
    case 4: self = .comparisonLe
    case 5: self = .comparisonEq
    case 6: self = .comparisonNe
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .comparisonUnspecified: return try container.encode("COMPARISON_UNSPECIFIED")
    case .comparisonGt: return try container.encode("COMPARISON_GT")
    case .comparisonGe: return try container.encode("COMPARISON_GE")
    case .comparisonLt: return try container.encode("COMPARISON_LT")
    case .comparisonLe: return try container.encode("COMPARISON_LE")
    case .comparisonEq: return try container.encode("COMPARISON_EQ")
    case .comparisonNe: return try container.encode("COMPARISON_NE")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
