// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The protocol for the `CreateAlertPolicy` request.
public struct CreateAlertPolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) in which
  /// to create the alerting policy. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///
  /// Note that this field names the parent container in which the alerting
  /// policy will be written, not the name of the created policy. |name| must be
  /// a host project of a Metrics Scope, otherwise INVALID_ARGUMENT error will
  /// return. The alerting policy that is returned will have a name that contains
  /// a normalized representation of this name as a prefix but adds a suffix of
  /// the form `/alertPolicies/[ALERT_POLICY_ID]`, identifying the policy in the
  /// container.
  public var name: Swift.String = Swift.String()

  /// Required. The requested alerting policy. You should omit the `name` field
  /// in this policy. The name will be returned in the new policy, including a
  /// new `[ALERT_POLICY_ID]` value.
  public var alertPolicy: AlertPolicy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAlertPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAlertPolicyRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let alertPolicy = CodingKeys(stringValue: "alertPolicy")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "alertPolicy",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.alertPolicy = try container.decodeIfPresent(AlertPolicy.self, forKey: .alertPolicy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.alertPolicy, forKey: .alertPolicy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CreateAlertPolicyRequest`: `"type.googleapis.com/google.monitoring.v3.CreateAlertPolicyRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.CreateAlertPolicyRequest"
  }

  /// Initialize an instance of `CreateAlertPolicyRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.CreateAlertPolicyRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CreateAlertPolicyRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
