// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `GetServiceLevelObjective` request.
public struct GetServiceLevelObjectiveRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the `ServiceLevelObjective` to get. The format
  /// is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/services/[SERVICE_ID]/serviceLevelObjectives/[SLO_NAME]
  public var name: Swift.String = Swift.String()

  /// View of the `ServiceLevelObjective` to return. If `DEFAULT`, return the
  /// `ServiceLevelObjective` as originally defined. If `EXPLICIT` and the
  /// `ServiceLevelObjective` is defined in terms of a `BasicSli`, replace the
  /// `BasicSli` with a `RequestBasedSli` spelling out how the SLI is computed.
  public var view: ServiceLevelObjective.View = ServiceLevelObjective.View()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GetServiceLevelObjectiveRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetServiceLevelObjectiveRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let view = CodingKeys(stringValue: "view")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "view",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(ServiceLevelObjective.View.self, forKey: .view) {
      self.view = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.view, forKey: .view)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `GetServiceLevelObjectiveRequest`: `"type.googleapis.com/google.monitoring.v3.GetServiceLevelObjectiveRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.GetServiceLevelObjectiveRequest"
  }

  /// Initialize an instance of `GetServiceLevelObjectiveRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.GetServiceLevelObjectiveRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `GetServiceLevelObjectiveRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
