// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An internal checker allows Uptime checks to run on private/internal GCP
/// resources.
@available(*, deprecated)
public struct InternalChecker: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique resource name for this InternalChecker. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/internalCheckers/[INTERNAL_CHECKER_ID]
  ///
  /// `[PROJECT_ID_OR_NUMBER]` is the Cloud Monitoring Metrics Scope project for
  /// the Uptime check config associated with the internal checker.
  public var name: Swift.String = Swift.String()

  /// The checker's human-readable name. The display name
  /// should be unique within a Cloud Monitoring Metrics Scope in order to make
  /// it easier to identify; however, uniqueness is not enforced.
  public var displayName: Swift.String = Swift.String()

  /// The [GCP VPC network](https://cloud.google.com/vpc/docs/vpc) where the
  /// internal resource lives (ex: "default").
  public var network: Swift.String = Swift.String()

  /// The GCP zone the Uptime check should egress from. Only respected for
  /// internal Uptime checks, where internal_network is specified.
  public var gcpZone: Swift.String = Swift.String()

  /// The GCP project ID where the internal checker lives. Not necessary
  /// the same as the Metrics Scope project.
  public var peerProjectId: Swift.String = Swift.String()

  /// The current operational state of the internal checker.
  public var state: InternalChecker.State = InternalChecker.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InternalChecker`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InternalChecker().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let network = CodingKeys(stringValue: "network")
    static let gcpZone = CodingKeys(stringValue: "gcpZone")
    static let peerProjectId = CodingKeys(stringValue: "peerProjectId")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "network",
      "gcpZone",
      "peerProjectId",
      "state",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpZone) {
      self.gcpZone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerProjectId) {
      self.peerProjectId = value
    }
    if let value = try container.decodeIfPresent(InternalChecker.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.gcpZone, forKey: .gcpZone)
    try container.encode(self.peerProjectId, forKey: .peerProjectId)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Operational states for an internal checker.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// An internal checker should never be in the unspecified state.
    case unspecified
    /// The checker is being created, provisioned, and configured. A checker in
    /// this state can be returned by `ListInternalCheckers` or
    /// `GetInternalChecker`, as well as by examining the [long running
    /// Operation](https://cloud.google.com/apis/design/design_patterns#long_running_operations)
    /// that created it.
    case creating
    /// The checker is running and available for use. A checker in this state
    /// can be returned by `ListInternalCheckers` or `GetInternalChecker` as
    /// well as by examining the [long running
    /// Operation](https://cloud.google.com/apis/design/design_patterns#long_running_operations)
    /// that created it.
    /// If a checker is being torn down, it is neither visible nor usable, so
    /// there is no "deleting" or "down" state.
    case running
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .running: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .creating: return "CREATING"
      case .running: return "RUNNING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "RUNNING": self = .running
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .running
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .running: return try container.encode("RUNNING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.InternalChecker"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
