// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `ListTimeSeries` request.
public struct ListTimeSeriesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name),
  /// organization or folder on which to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///     organizations/[ORGANIZATION_ID]
  ///     folders/[FOLDER_ID]
  public var name: Swift.String = Swift.String()

  /// Required. A [monitoring
  /// filter](https://cloud.google.com/monitoring/api/v3/filters) that specifies
  /// which time series should be returned.  The filter must specify a single
  /// metric type, and can additionally specify metric labels and other
  /// information. For example:
  ///
  ///     metric.type = "compute.googleapis.com/instance/cpu/usage_time" AND
  ///         metric.labels.instance_name = "my-instance-name"
  public var filter: Swift.String = Swift.String()

  /// Required. The time interval for which results should be returned. Only time
  /// series that contain data points in the specified interval are included in
  /// the response.
  public var interval: TimeInterval? = nil

  /// Specifies the alignment of data points in individual time series as
  /// well as how to combine the retrieved time series across specified labels.
  ///
  /// By default (if no `aggregation` is explicitly specified), the raw time
  /// series data is returned.
  public var aggregation: Aggregation? = nil

  /// Apply a second aggregation after `aggregation` is applied. May only be
  /// specified if `aggregation` is specified.
  public var secondaryAggregation: Aggregation? = nil

  /// Unsupported: must be left blank. The points in each time series are
  /// currently returned in reverse time order (most recent to oldest).
  public var orderBy: Swift.String = Swift.String()

  /// Required. Specifies which information is returned about the time series.
  public var view: ListTimeSeriesRequest.TimeSeriesView = ListTimeSeriesRequest.TimeSeriesView()

  /// A positive number that is the maximum number of results to return. If
  /// `page_size` is empty or more than 100,000 results, the effective
  /// `page_size` is 100,000 results. If `view` is set to `FULL`, this is the
  /// maximum number of `Points` returned. If `view` is set to `HEADERS`, this is
  /// the maximum number of `TimeSeries` returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListTimeSeriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTimeSeriesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let filter = CodingKeys(stringValue: "filter")
    static let interval = CodingKeys(stringValue: "interval")
    static let aggregation = CodingKeys(stringValue: "aggregation")
    static let secondaryAggregation = CodingKeys(stringValue: "secondaryAggregation")
    static let orderBy = CodingKeys(stringValue: "orderBy")
    static let view = CodingKeys(stringValue: "view")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "filter",
      "interval",
      "aggregation",
      "secondaryAggregation",
      "orderBy",
      "view",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    self.interval = try container.decodeIfPresent(TimeInterval.self, forKey: .interval)
    self.aggregation = try container.decodeIfPresent(Aggregation.self, forKey: .aggregation)
    self.secondaryAggregation = try container.decodeIfPresent(
      Aggregation.self, forKey: .secondaryAggregation)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    if let value = try container.decodeIfPresent(
      ListTimeSeriesRequest.TimeSeriesView.self, forKey: .view)
    {
      self.view = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.filter, forKey: .filter)
    try container.encodeIfPresent(self.interval, forKey: .interval)
    try container.encodeIfPresent(self.aggregation, forKey: .aggregation)
    try container.encodeIfPresent(self.secondaryAggregation, forKey: .secondaryAggregation)
    try container.encode(self.orderBy, forKey: .orderBy)
    try container.encode(self.view, forKey: .view)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Controls which fields are returned by `ListTimeSeries*`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TimeSeriesView: Codable, Equatable, Hashable, Sendable {
    /// Returns the identity of the metric(s), the time series,
    /// and the time series data.
    case full
    /// Returns the identity of the metric and the time series resource,
    /// but not the time series data.
    case headers
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .full
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .full: return 0
      case .headers: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .full: return "FULL"
      case .headers: return "HEADERS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TimeSeriesView/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FULL": self = .full
      case "HEADERS": self = .headers
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TimeSeriesView/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .full
      case 1: self = .headers
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .full: return try container.encode("FULL")
      case .headers: return try container.encode("HEADERS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListTimeSeriesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
