// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The protocol for the `ListUptimeCheckConfigs` response.
public struct ListUptimeCheckConfigsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The returned Uptime check configurations.
  public var uptimeCheckConfigs: [UptimeCheckConfig] = []

  /// This field represents the pagination token to retrieve the next page of
  /// results. If the value is empty, it means no further results for the
  /// request. To retrieve the next page of results, the value of the
  /// next_page_token is passed to the subsequent List method call (in the
  /// request message's page_token field).
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of Uptime check configurations for the project,
  /// irrespective of any pagination.
  public var totalSize: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListUptimeCheckConfigsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListUptimeCheckConfigsResponse().with { $0.uptimeCheckConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uptimeCheckConfigs = CodingKeys(stringValue: "uptimeCheckConfigs")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")

    static let _knownKeys: Set<Swift.String> = [
      "uptimeCheckConfigs",
      "nextPageToken",
      "totalSize",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [UptimeCheckConfig].self, forKey: .uptimeCheckConfigs)
    {
      self.uptimeCheckConfigs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uptimeCheckConfigs, forKey: .uptimeCheckConfigs)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ListUptimeCheckConfigsResponse`: `"type.googleapis.com/google.monitoring.v3.ListUptimeCheckConfigsResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListUptimeCheckConfigsResponse"
  }

  /// Initialize an instance of `ListUptimeCheckConfigsResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.ListUptimeCheckConfigsResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListUptimeCheckConfigsResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListUptimeCheckConfigsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [UptimeCheckConfig] {
    return self.uptimeCheckConfigs
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
