// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `ListServiceLevelObjectives` request.
public struct ListServiceLevelObjectivesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the parent containing the listed SLOs, either a
  /// project or a Monitoring Metrics Scope. The formats are:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/services/[SERVICE_ID]
  ///     workspaces/[HOST_PROJECT_ID_OR_NUMBER]/services/-
  public var parent: Swift.String = Swift.String()

  /// A filter specifying what `ServiceLevelObjective`s to return.
  public var filter: Swift.String = Swift.String()

  /// A non-negative number that is the maximum number of results to return.
  /// When 0, use default page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  public var pageToken: Swift.String = Swift.String()

  /// View of the `ServiceLevelObjective`s to return. If `DEFAULT`, return each
  /// `ServiceLevelObjective` as originally defined. If `EXPLICIT` and the
  /// `ServiceLevelObjective` is defined in terms of a `BasicSli`, replace the
  /// `BasicSli` with a `RequestBasedSli` spelling out how the SLI is computed.
  public var view: ServiceLevelObjective.View = ServiceLevelObjective.View()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListServiceLevelObjectivesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListServiceLevelObjectivesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let filter = CodingKeys(stringValue: "filter")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let view = CodingKeys(stringValue: "view")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "filter",
      "pageSize",
      "pageToken",
      "view",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(ServiceLevelObjective.View.self, forKey: .view) {
      self.view = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.view, forKey: .view)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListServiceLevelObjectivesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
