// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The protocol for the `ListAlertPolicies` request.
public struct ListAlertPoliciesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) whose
  /// alert policies are to be listed. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///
  /// Note that this field names the parent container in which the alerting
  /// policies to be listed are stored. To retrieve a single alerting policy
  /// by name, use the
  /// [GetAlertPolicy][google.monitoring.v3.AlertPolicyService.GetAlertPolicy]
  /// operation, instead.
  ///
  /// [google.monitoring.v3.AlertPolicyService.GetAlertPolicy]: <doc:AlertPolicyServiceClient/getAlertPolicy(request:options:)>
  public var name: Swift.String = Swift.String()

  /// Optional. If provided, this field specifies the criteria that must be met
  /// by alert policies to be included in the response.
  ///
  /// For more details, see [sorting and
  /// filtering](https://cloud.google.com/monitoring/api/v3/sorting-and-filtering).
  public var filter: Swift.String = Swift.String()

  /// Optional. A comma-separated list of fields by which to sort the result.
  /// Supports the same set of field references as the `filter` field. Entries
  /// can be prefixed with a minus sign to sort by the field in descending order.
  ///
  /// For more details, see [sorting and
  /// filtering](https://cloud.google.com/monitoring/api/v3/sorting-and-filtering).
  public var orderBy: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return in a single response.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. If this field is not empty then it must contain the
  /// `nextPageToken` value returned by a previous call to this method.  Using
  /// this field causes the method to return more results from the previous
  /// method call.
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListAlertPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAlertPoliciesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "filter",
      "orderBy",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ListAlertPoliciesRequest`: `"type.googleapis.com/google.monitoring.v3.ListAlertPoliciesRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListAlertPoliciesRequest"
  }

  /// Initialize an instance of `ListAlertPoliciesRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.ListAlertPoliciesRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListAlertPoliciesRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
