// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `ListGroup` request.
public struct ListGroupsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) whose
  /// groups are to be listed. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  public var name: Swift.String = Swift.String()

  /// A positive number that is the maximum number of results to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// If this field is not empty then it must contain the `next_page_token` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  public var pageToken: Swift.String = Swift.String()

  /// An optional filter consisting of a single group name.  The filters limit
  /// the groups returned based on their parent-child relationship with the
  /// specified group. If no filter is specified, all groups are returned.
  public var filter: FilterOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListGroupsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListGroupsRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let childrenOfGroup = CodingKeys(stringValue: "childrenOfGroup")
    static let ancestorsOfGroup = CodingKeys(stringValue: "ancestorsOfGroup")
    static let descendantsOfGroup = CodingKeys(stringValue: "descendantsOfGroup")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "childrenOfGroup",
      "ancestorsOfGroup",
      "descendantsOfGroup",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }

    var filter: FilterOneOf? = nil
    let filterCheckAndSet = {
      if filter != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'filter'"))
      }
      filter = $0
    }
    if let childrenOfGroup = try container.decodeIfPresent(
      Swift.String.self, forKey: .childrenOfGroup)
    {
      try filterCheckAndSet(.childrenOfGroup(childrenOfGroup))
    }
    if let ancestorsOfGroup = try container.decodeIfPresent(
      Swift.String.self, forKey: .ancestorsOfGroup)
    {
      try filterCheckAndSet(.ancestorsOfGroup(ancestorsOfGroup))
    }
    if let descendantsOfGroup = try container.decodeIfPresent(
      Swift.String.self, forKey: .descendantsOfGroup)
    {
      try filterCheckAndSet(.descendantsOfGroup(descendantsOfGroup))
    }
    self.filter = filter
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)

    if let choice = self.filter {
      switch choice {
      case .childrenOfGroup(let value):
        try container.encode(value, forKey: .childrenOfGroup)
      case .ancestorsOfGroup(let value):
        try container.encode(value, forKey: .ancestorsOfGroup)
      case .descendantsOfGroup(let value):
        try container.encode(value, forKey: .descendantsOfGroup)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An optional filter consisting of a single group name.  The filters limit
  /// the groups returned based on their parent-child relationship with the
  /// specified group. If no filter is specified, all groups are returned.
  public enum FilterOneOf: Codable, Equatable, Sendable {
    /// A group name. The format is:
    ///
    ///     projects/[PROJECT_ID_OR_NUMBER]/groups/[GROUP_ID]
    ///
    /// Returns groups whose `parent_name` field contains the group
    /// name.  If no groups have this parent, the results are empty.
    case childrenOfGroup(Swift.String)
    /// A group name. The format is:
    ///
    ///     projects/[PROJECT_ID_OR_NUMBER]/groups/[GROUP_ID]
    ///
    /// Returns groups that are ancestors of the specified group.
    /// The groups are returned in order, starting with the immediate parent and
    /// ending with the most distant ancestor.  If the specified group has no
    /// immediate parent, the results are empty.
    case ancestorsOfGroup(Swift.String)
    /// A group name. The format is:
    ///
    ///     projects/[PROJECT_ID_OR_NUMBER]/groups/[GROUP_ID]
    ///
    /// Returns the descendants of the specified group.  This is a superset of
    /// the results returned by the `children_of_group` filter, and includes
    /// children-of-children, and so forth.
    case descendantsOfGroup(Swift.String)
  }

  /// The type URL for `ListGroupsRequest`: `"type.googleapis.com/google.monitoring.v3.ListGroupsRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ListGroupsRequest"
  }

  /// Initialize an instance of `ListGroupsRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.ListGroupsRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListGroupsRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
