// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleApi
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages metric descriptors, monitored resource descriptors, and
/// time series data.
///
/// @Snippet(path: "MetricServiceQuickstart")
public final class MetricServiceClient: Clients.MetricServiceProtocol, Sendable {
  let inner: any Clients.MetricServiceStub

  /// Creates a new `MetricServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.MetricServiceStub = try Clients.MetricServiceTransport(options)
    inner = Clients.MetricServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MetricServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists monitored resource descriptors that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListMonitoredResourceDescriptors")
  public func listMonitoredResourceDescriptors(
    request: ListMonitoredResourceDescriptorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse {
    try await self.inner.listMonitoredResourceDescriptors(request: request, options: options)
  }

  /// Gets a single monitored resource descriptor.
  ///
  /// @Snippet(path: "MetricService_GetMonitoredResourceDescriptor")
  public func getMonitoredResourceDescriptor(
    request: GetMonitoredResourceDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MonitoredResourceDescriptor {
    try await self.inner.getMonitoredResourceDescriptor(request: request, options: options)
  }

  /// Lists metric descriptors that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListMetricDescriptors")
  public func listMetricDescriptors(
    request: ListMetricDescriptorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse {
    try await self.inner.listMetricDescriptors(request: request, options: options)
  }

  /// Gets a single metric descriptor.
  ///
  /// @Snippet(path: "MetricService_GetMetricDescriptor")
  public func getMetricDescriptor(
    request: GetMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MetricDescriptor {
    try await self.inner.getMetricDescriptor(request: request, options: options)
  }

  /// Creates a new metric descriptor.
  /// The creation is executed asynchronously.
  /// User-created metric descriptors define
  /// [custom metrics](https://cloud.google.com/monitoring/custom-metrics).
  /// The metric descriptor is updated if it already exists,
  /// except that metric labels are never removed.
  ///
  /// @Snippet(path: "MetricService_CreateMetricDescriptor")
  public func createMetricDescriptor(
    request: CreateMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MetricDescriptor {
    try await self.inner.createMetricDescriptor(request: request, options: options)
  }

  /// Deletes a metric descriptor. Only user-created
  /// [custom metrics](https://cloud.google.com/monitoring/custom-metrics) can be
  /// deleted.
  ///
  /// @Snippet(path: "MetricService_DeleteMetricDescriptor")
  public func deleteMetricDescriptor(
    request: DeleteMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteMetricDescriptor(request: request, options: options)
  }

  /// Lists time series that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListTimeSeries")
  public func listTimeSeries(
    request: ListTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse {
    try await self.inner.listTimeSeries(request: request, options: options)
  }

  /// Creates or adds data to one or more time series.
  /// The response is empty if all time series in the request were written.
  /// If any time series could not be written, a corresponding failure message is
  /// included in the error response.
  /// This method does not support
  /// [resource locations constraint of an organization
  /// policy](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy).
  ///
  /// @Snippet(path: "MetricService_CreateTimeSeries")
  public func createTimeSeries(
    request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.createTimeSeries(request: request, options: options)
  }

  /// Creates or adds data to one or more service time series. A service time
  /// series is a time series for a metric from a Google Cloud service. The
  /// response is empty if all time series in the request were written. If any
  /// time series could not be written, a corresponding failure message is
  /// included in the error response. This endpoint rejects writes to
  /// user-defined metrics.
  /// This method is only for use by Google Cloud services. Use
  /// [projects.timeSeries.create][google.monitoring.v3.MetricService.CreateTimeSeries]
  /// instead.
  ///
  /// [google.monitoring.v3.MetricService.CreateTimeSeries]: <doc:MetricServiceClient/createTimeSeries(request:options:)>
  ///
  /// @Snippet(path: "MetricService_CreateServiceTimeSeries")
  public func createServiceTimeSeries(
    request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.createServiceTimeSeries(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MetricServiceClient`.
  ///
  /// To mock `MetricServiceClient` change your functions to receive
  /// `some MetricServiceProtocol` or `any MetricServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MetricServiceProtocol: Sendable {
    /// See `MetricServiceClient.listMonitoredResourceDescriptors`.
    func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse

    /// See `MetricServiceClient.getMonitoredResourceDescriptor`.
    func getMonitoredResourceDescriptor(
      request: GetMonitoredResourceDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MonitoredResourceDescriptor

    /// See `MetricServiceClient.listMetricDescriptors`.
    func listMetricDescriptors(
      request: ListMetricDescriptorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse

    /// See `MetricServiceClient.getMetricDescriptor`.
    func getMetricDescriptor(
      request: GetMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    /// See `MetricServiceClient.createMetricDescriptor`.
    func createMetricDescriptor(
      request: CreateMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.MetricDescriptor

    /// See `MetricServiceClient.deleteMetricDescriptor`.
    func deleteMetricDescriptor(
      request: DeleteMetricDescriptorRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `MetricServiceClient.listTimeSeries`.
    func listTimeSeries(
      request: ListTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse

    /// See `MetricServiceClient.createTimeSeries`.
    func createTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `MetricServiceClient.createServiceTimeSeries`.
    func createServiceTimeSeries(
      request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.MetricServiceProtocol {
  public func listMonitoredResourceDescriptors(request: ListMonitoredResourceDescriptorsRequest)
    async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse
  {
    try await self.listMonitoredResourceDescriptors(request: request, options: .init())
  }

  public func listMonitoredResourceDescriptors(
    request: ListMonitoredResourceDescriptorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMonitoredResourceDescriptorsByItems(
    request: ListMonitoredResourceDescriptorsRequest
  ) -> some AsyncSequence<GoogleApi.MonitoredResourceDescriptor, any Swift.Error> & Sendable {
    self.listMonitoredResourceDescriptorsByItems(request: request, options: .init())
  }

  /// Lists monitored resource descriptors that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListMonitoredResourceDescriptors")
  public func listMonitoredResourceDescriptorsByItems(
    request: ListMonitoredResourceDescriptorsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleApi.MonitoredResourceDescriptor, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListMonitoredResourceDescriptorsResponse in
      var request = request
      request.pageToken = token
      return try await self.listMonitoredResourceDescriptors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listMonitoredResourceDescriptorsByItems(
    name: Swift.String,
  ) -> some AsyncSequence<GoogleApi.MonitoredResourceDescriptor, any Swift.Error> & Sendable {
    let request = ListMonitoredResourceDescriptorsRequest().with {
      $0.name = name
    }
    return self.listMonitoredResourceDescriptorsByItems(request: request)
  }

  public func getMonitoredResourceDescriptor(request: GetMonitoredResourceDescriptorRequest)
    async throws -> GoogleApi.MonitoredResourceDescriptor
  {
    try await self.getMonitoredResourceDescriptor(request: request, options: .init())
  }

  public func getMonitoredResourceDescriptor(
    request: GetMonitoredResourceDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MonitoredResourceDescriptor {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMonitoredResourceDescriptor(
    name: Swift.String,
  ) async throws -> GoogleApi.MonitoredResourceDescriptor {
    let request = GetMonitoredResourceDescriptorRequest().with {
      $0.name = name
    }
    return try await self.getMonitoredResourceDescriptor(request: request)
  }

  public func listMetricDescriptors(request: ListMetricDescriptorsRequest) async throws
    -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse
  {
    try await self.listMetricDescriptors(request: request, options: .init())
  }

  public func listMetricDescriptors(
    request: ListMetricDescriptorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMetricDescriptorsByItems(
    request: ListMetricDescriptorsRequest
  ) -> some AsyncSequence<GoogleApi.MetricDescriptor, any Swift.Error> & Sendable {
    self.listMetricDescriptorsByItems(request: request, options: .init())
  }

  /// Lists metric descriptors that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListMetricDescriptors")
  public func listMetricDescriptorsByItems(
    request: ListMetricDescriptorsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleApi.MetricDescriptor, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListMetricDescriptorsResponse in
      var request = request
      request.pageToken = token
      return try await self.listMetricDescriptors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listMetricDescriptorsByItems(
    name: Swift.String,
  ) -> some AsyncSequence<GoogleApi.MetricDescriptor, any Swift.Error> & Sendable {
    let request = ListMetricDescriptorsRequest().with {
      $0.name = name
    }
    return self.listMetricDescriptorsByItems(request: request)
  }

  public func getMetricDescriptor(request: GetMetricDescriptorRequest) async throws
    -> GoogleApi.MetricDescriptor
  {
    try await self.getMetricDescriptor(request: request, options: .init())
  }

  public func getMetricDescriptor(
    request: GetMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MetricDescriptor {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMetricDescriptor(
    name: Swift.String,
  ) async throws -> GoogleApi.MetricDescriptor {
    let request = GetMetricDescriptorRequest().with {
      $0.name = name
    }
    return try await self.getMetricDescriptor(request: request)
  }

  public func createMetricDescriptor(request: CreateMetricDescriptorRequest) async throws
    -> GoogleApi.MetricDescriptor
  {
    try await self.createMetricDescriptor(request: request, options: .init())
  }

  public func createMetricDescriptor(
    request: CreateMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApi.MetricDescriptor {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createMetricDescriptor(
    name: Swift.String,
    metricDescriptor: GoogleApi.MetricDescriptor?,
  ) async throws -> GoogleApi.MetricDescriptor {
    let request = CreateMetricDescriptorRequest().with {
      $0.name = name
      $0.metricDescriptor = metricDescriptor
    }
    return try await self.createMetricDescriptor(request: request)
  }

  public func deleteMetricDescriptor(request: DeleteMetricDescriptorRequest) async throws {
    try await self.deleteMetricDescriptor(request: request, options: .init())
  }

  public func deleteMetricDescriptor(
    request: DeleteMetricDescriptorRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteMetricDescriptor(
    name: Swift.String,
  ) async throws {
    let request = DeleteMetricDescriptorRequest().with {
      $0.name = name
    }
    try await self.deleteMetricDescriptor(request: request)
  }

  public func listTimeSeries(request: ListTimeSeriesRequest) async throws
    -> GoogleCloudMonitoringV3.ListTimeSeriesResponse
  {
    try await self.listTimeSeries(request: request, options: .init())
  }

  public func listTimeSeries(
    request: ListTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTimeSeriesByItems(
    request: ListTimeSeriesRequest
  ) -> some AsyncSequence<TimeSeries, any Swift.Error> & Sendable {
    self.listTimeSeriesByItems(request: request, options: .init())
  }

  /// Lists time series that match a filter.
  ///
  /// @Snippet(path: "MetricService_ListTimeSeries")
  public func listTimeSeriesByItems(
    request: ListTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<TimeSeries, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListTimeSeriesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listTimeSeries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listTimeSeriesByItems(
    name: Swift.String,
    filter: Swift.String,
    interval: TimeInterval?,
    view: ListTimeSeriesRequest.TimeSeriesView,
  ) -> some AsyncSequence<TimeSeries, any Swift.Error> & Sendable {
    let request = ListTimeSeriesRequest().with {
      $0.name = name
      $0.filter = filter
      $0.interval = interval
      $0.view = view
    }
    return self.listTimeSeriesByItems(request: request)
  }

  public func createTimeSeries(request: CreateTimeSeriesRequest) async throws {
    try await self.createTimeSeries(request: request, options: .init())
  }

  public func createTimeSeries(
    request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTimeSeries(
    name: Swift.String,
    timeSeries: [TimeSeries],
  ) async throws {
    let request = CreateTimeSeriesRequest().with {
      $0.name = name
      $0.timeSeries = timeSeries
    }
    try await self.createTimeSeries(request: request)
  }

  public func createServiceTimeSeries(request: CreateTimeSeriesRequest) async throws {
    try await self.createServiceTimeSeries(request: request, options: .init())
  }

  public func createServiceTimeSeries(
    request: CreateTimeSeriesRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceTimeSeries(
    name: Swift.String,
    timeSeries: [TimeSeries],
  ) async throws {
    let request = CreateTimeSeriesRequest().with {
      $0.name = name
      $0.timeSeries = timeSeries
    }
    try await self.createServiceTimeSeries(request: request)
  }
}
