// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A single data point in a time series.
public struct Point: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time interval to which the data point applies.  For `GAUGE` metrics,
  /// the start time is optional, but if it is supplied, it must equal the
  /// end time.  For `DELTA` metrics, the start
  /// and end time should specify a non-zero interval, with subsequent points
  /// specifying contiguous and non-overlapping intervals.  For `CUMULATIVE`
  /// metrics, the start and end time should specify a non-zero interval, with
  /// subsequent points specifying the same start time and increasing end times,
  /// until an event resets the cumulative value to zero and sets a new start
  /// time for the following points.
  public var interval: TimeInterval? = nil

  /// The value of the data point.
  public var value: TypedValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Point`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Point().with { $0.interval = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let interval = CodingKeys(stringValue: "interval")
    static let value = CodingKeys(stringValue: "value")

    static let _knownKeys: Set<Swift.String> = [
      "interval",
      "value",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.interval = try container.decodeIfPresent(TimeInterval.self, forKey: .interval)
    self.value = try container.decodeIfPresent(TypedValue.self, forKey: .value)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.interval, forKey: .interval)
    try container.encodeIfPresent(self.value, forKey: .value)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Point`: `"type.googleapis.com/google.monitoring.v3.Point"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.Point"
  }

  /// Initialize an instance of `Point` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.Point"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Point` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
