// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The `QueryTimeSeries` response. For information about the status of
/// Monitoring Query Language (MQL), see the [MQL deprecation
/// notice](https://cloud.google.com/stackdriver/docs/deprecations/mql).
@available(*, deprecated)
public struct QueryTimeSeriesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The descriptor for the time series data.
  public var timeSeriesDescriptor: TimeSeriesDescriptor? = nil

  /// The time series data.
  public var timeSeriesData: [TimeSeriesData] = []

  /// If there are more results than have been returned, then this field is set
  /// to a non-empty value.  To see the additional results, use that value as
  /// `page_token` in the next call to this method.
  public var nextPageToken: Swift.String = Swift.String()

  /// Query execution errors that may have caused the time series data returned
  /// to be incomplete. The available data will be available in the
  /// response.
  public var partialErrors: [GoogleRpc.Status] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QueryTimeSeriesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryTimeSeriesResponse().with { $0.timeSeriesDescriptor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let timeSeriesDescriptor = CodingKeys(stringValue: "timeSeriesDescriptor")
    static let timeSeriesData = CodingKeys(stringValue: "timeSeriesData")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let partialErrors = CodingKeys(stringValue: "partialErrors")

    static let _knownKeys: Set<Swift.String> = [
      "timeSeriesDescriptor",
      "timeSeriesData",
      "nextPageToken",
      "partialErrors",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.timeSeriesDescriptor = try container.decodeIfPresent(
      TimeSeriesDescriptor.self, forKey: .timeSeriesDescriptor)
    if let value = try container.decodeIfPresent([TimeSeriesData].self, forKey: .timeSeriesData) {
      self.timeSeriesData = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .partialErrors) {
      self.partialErrors = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.timeSeriesDescriptor, forKey: .timeSeriesDescriptor)
    try container.encode(self.timeSeriesData, forKey: .timeSeriesData)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.partialErrors, forKey: .partialErrors)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `QueryTimeSeriesResponse`: `"type.googleapis.com/google.monitoring.v3.QueryTimeSeriesResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.QueryTimeSeriesResponse"
  }

  /// Initialize an instance of `QueryTimeSeriesResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.QueryTimeSeriesResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `QueryTimeSeriesResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@available(*, deprecated)
@_spi(GoogleCloudInternal)
extension QueryTimeSeriesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [TimeSeriesData] {
    return self.timeSeriesData
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
