// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// The Cloud Monitoring Service-Oriented Monitoring API has endpoints for
/// managing and querying aspects of a Metrics Scope's services. These include
/// the `Service`'s monitored resources, its Service-Level Objectives, and a
/// taxonomy of categorized Health Metrics.
///
/// @Snippet(path: "ServiceMonitoringServiceQuickstart")
public final class ServiceMonitoringServiceClient: Clients.ServiceMonitoringServiceProtocol,
  Sendable
{
  let inner: any Clients.ServiceMonitoringServiceStub

  /// Creates a new `ServiceMonitoringServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServiceMonitoringServiceStub =
      try Clients.ServiceMonitoringServiceTransport(options)
    inner = Clients.ServiceMonitoringServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServiceMonitoringServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create a `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_CreateService")
  public func createService(
    request: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    try await self.inner.createService(request: request, options: options)
  }

  /// Get the named `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_GetService")
  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    try await self.inner.getService(request: request, options: options)
  }

  /// List `Service`s for this Metrics Scope.
  ///
  /// @Snippet(path: "ServiceMonitoringService_ListServices")
  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListServicesResponse {
    try await self.inner.listServices(request: request, options: options)
  }

  /// Update this `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_UpdateService")
  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    try await self.inner.updateService(request: request, options: options)
  }

  /// Soft delete this `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_DeleteService")
  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteService(request: request, options: options)
  }

  /// Create a `ServiceLevelObjective` for the given `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_CreateServiceLevelObjective")
  public func createServiceLevelObjective(
    request: CreateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    try await self.inner.createServiceLevelObjective(request: request, options: options)
  }

  /// Get a `ServiceLevelObjective` by name.
  ///
  /// @Snippet(path: "ServiceMonitoringService_GetServiceLevelObjective")
  public func getServiceLevelObjective(
    request: GetServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    try await self.inner.getServiceLevelObjective(request: request, options: options)
  }

  /// List the `ServiceLevelObjective`s for the given `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_ListServiceLevelObjectives")
  public func listServiceLevelObjectives(
    request: ListServiceLevelObjectivesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse {
    try await self.inner.listServiceLevelObjectives(request: request, options: options)
  }

  /// Update the given `ServiceLevelObjective`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_UpdateServiceLevelObjective")
  public func updateServiceLevelObjective(
    request: UpdateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    try await self.inner.updateServiceLevelObjective(request: request, options: options)
  }

  /// Delete the given `ServiceLevelObjective`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_DeleteServiceLevelObjective")
  public func deleteServiceLevelObjective(
    request: DeleteServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteServiceLevelObjective(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServiceMonitoringServiceClient`.
  ///
  /// To mock `ServiceMonitoringServiceClient` change your functions to receive
  /// `some ServiceMonitoringServiceProtocol` or `any ServiceMonitoringServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServiceMonitoringServiceProtocol: Sendable {
    /// See `ServiceMonitoringServiceClient.createService`.
    func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service

    /// See `ServiceMonitoringServiceClient.getService`.
    func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service

    /// See `ServiceMonitoringServiceClient.listServices`.
    func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListServicesResponse

    /// See `ServiceMonitoringServiceClient.updateService`.
    func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.Service

    /// See `ServiceMonitoringServiceClient.deleteService`.
    func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ServiceMonitoringServiceClient.createServiceLevelObjective`.
    func createServiceLevelObjective(
      request: CreateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective

    /// See `ServiceMonitoringServiceClient.getServiceLevelObjective`.
    func getServiceLevelObjective(
      request: GetServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective

    /// See `ServiceMonitoringServiceClient.listServiceLevelObjectives`.
    func listServiceLevelObjectives(
      request: ListServiceLevelObjectivesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse

    /// See `ServiceMonitoringServiceClient.updateServiceLevelObjective`.
    func updateServiceLevelObjective(
      request: UpdateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective

    /// See `ServiceMonitoringServiceClient.deleteServiceLevelObjective`.
    func deleteServiceLevelObjective(
      request: DeleteServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ServiceMonitoringServiceProtocol {
  public func createService(request: CreateServiceRequest) async throws
    -> GoogleCloudMonitoringV3.Service
  {
    try await self.createService(request: request, options: .init())
  }

  public func createService(
    request: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createService(
    parent: Swift.String,
    service: Service?,
  ) async throws -> GoogleCloudMonitoringV3.Service {
    let request = CreateServiceRequest().with {
      $0.parent = parent
      $0.service = service
    }
    return try await self.createService(request: request)
  }

  public func getService(request: GetServiceRequest) async throws -> GoogleCloudMonitoringV3.Service
  {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getService(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringV3.Service {
    let request = GetServiceRequest().with {
      $0.name = name
    }
    return try await self.getService(request: request)
  }

  public func listServices(request: ListServicesRequest) async throws
    -> GoogleCloudMonitoringV3.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListServicesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServicesByItems(
    request: ListServicesRequest
  ) -> some AsyncSequence<Service, any Swift.Error> & Sendable {
    self.listServicesByItems(request: request, options: .init())
  }

  /// List `Service`s for this Metrics Scope.
  ///
  /// @Snippet(path: "ServiceMonitoringService_ListServices")
  public func listServicesByItems(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Service, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudMonitoringV3.ListServicesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listServices(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServicesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Service, any Swift.Error> & Sendable {
    let request = ListServicesRequest().with {
      $0.parent = parent
    }
    return self.listServicesByItems(request: request)
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleCloudMonitoringV3.Service
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.Service {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateService(
    service: Service?,
  ) async throws -> GoogleCloudMonitoringV3.Service {
    let request = UpdateServiceRequest().with {
      $0.service = service
    }
    return try await self.updateService(request: request)
  }

  public func deleteService(request: DeleteServiceRequest) async throws {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteService(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceRequest().with {
      $0.name = name
    }
    try await self.deleteService(request: request)
  }

  public func createServiceLevelObjective(request: CreateServiceLevelObjectiveRequest) async throws
    -> GoogleCloudMonitoringV3.ServiceLevelObjective
  {
    try await self.createServiceLevelObjective(request: request, options: .init())
  }

  public func createServiceLevelObjective(
    request: CreateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceLevelObjective(
    parent: Swift.String,
    serviceLevelObjective: ServiceLevelObjective?,
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    let request = CreateServiceLevelObjectiveRequest().with {
      $0.parent = parent
      $0.serviceLevelObjective = serviceLevelObjective
    }
    return try await self.createServiceLevelObjective(request: request)
  }

  public func getServiceLevelObjective(request: GetServiceLevelObjectiveRequest) async throws
    -> GoogleCloudMonitoringV3.ServiceLevelObjective
  {
    try await self.getServiceLevelObjective(request: request, options: .init())
  }

  public func getServiceLevelObjective(
    request: GetServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceLevelObjective(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    let request = GetServiceLevelObjectiveRequest().with {
      $0.name = name
    }
    return try await self.getServiceLevelObjective(request: request)
  }

  public func listServiceLevelObjectives(request: ListServiceLevelObjectivesRequest) async throws
    -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse
  {
    try await self.listServiceLevelObjectives(request: request, options: .init())
  }

  public func listServiceLevelObjectives(
    request: ListServiceLevelObjectivesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceLevelObjectivesByItems(
    request: ListServiceLevelObjectivesRequest
  ) -> some AsyncSequence<ServiceLevelObjective, any Swift.Error> & Sendable {
    self.listServiceLevelObjectivesByItems(request: request, options: .init())
  }

  /// List the `ServiceLevelObjective`s for the given `Service`.
  ///
  /// @Snippet(path: "ServiceMonitoringService_ListServiceLevelObjectives")
  public func listServiceLevelObjectivesByItems(
    request: ListServiceLevelObjectivesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ServiceLevelObjective, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListServiceLevelObjectivesResponse in
      var request = request
      request.pageToken = token
      return try await self.listServiceLevelObjectives(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listServiceLevelObjectivesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ServiceLevelObjective, any Swift.Error> & Sendable {
    let request = ListServiceLevelObjectivesRequest().with {
      $0.parent = parent
    }
    return self.listServiceLevelObjectivesByItems(request: request)
  }

  public func updateServiceLevelObjective(request: UpdateServiceLevelObjectiveRequest) async throws
    -> GoogleCloudMonitoringV3.ServiceLevelObjective
  {
    try await self.updateServiceLevelObjective(request: request, options: .init())
  }

  public func updateServiceLevelObjective(
    request: UpdateServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServiceLevelObjective(
    serviceLevelObjective: ServiceLevelObjective?,
  ) async throws -> GoogleCloudMonitoringV3.ServiceLevelObjective {
    let request = UpdateServiceLevelObjectiveRequest().with {
      $0.serviceLevelObjective = serviceLevelObjective
    }
    return try await self.updateServiceLevelObjective(request: request)
  }

  public func deleteServiceLevelObjective(request: DeleteServiceLevelObjectiveRequest) async throws
  {
    try await self.deleteServiceLevelObjective(request: request, options: .init())
  }

  public func deleteServiceLevelObjective(
    request: DeleteServiceLevelObjectiveRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceLevelObjective(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceLevelObjectiveRequest().with {
      $0.name = name
    }
    try await self.deleteServiceLevelObjective(request: request)
  }
}
