// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Service-Level Objective (SLO) describes a level of desired good service. It
/// consists of a service-level indicator (SLI), a performance goal, and a period
/// over which the objective is to be evaluated against that goal. The SLO can
/// use SLIs defined in a number of different manners. Typical SLOs might include
/// "99% of requests in each rolling week have latency below 200 milliseconds" or
/// "99.5% of requests in each calendar month return successfully."
public struct ServiceLevelObjective: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name for this `ServiceLevelObjective`. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/services/[SERVICE_ID]/serviceLevelObjectives/[SLO_NAME]
  public var name: Swift.String = Swift.String()

  /// Name used for UI elements listing this SLO.
  public var displayName: Swift.String = Swift.String()

  /// The definition of good service, used to measure and calculate the quality
  /// of the `Service`'s performance with respect to a single aspect of service
  /// quality.
  public var serviceLevelIndicator: ServiceLevelIndicator? = nil

  /// The fraction of service that must be good in order for this objective to be
  /// met. `0 < goal <= 0.9999`.
  public var goal: Swift.Double = Swift.Double()

  /// Labels which have been used to annotate the service-level objective. Label
  /// keys must start with a letter. Label keys and values may contain lowercase
  /// letters, numbers, underscores, and dashes. Label keys and values have a
  /// maximum length of 63 characters, and must be less than 128 bytes in size.
  /// Up to 64 label entries may be stored. For labels which do not have a
  /// semantic value, the empty string may be supplied for the label value.
  public var userLabels: [Swift.String: Swift.String] = [:]

  /// The time period over which the objective will be evaluated.
  public var period: PeriodOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceLevelObjective`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceLevelObjective().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let serviceLevelIndicator = CodingKeys(stringValue: "serviceLevelIndicator")
    static let goal = CodingKeys(stringValue: "goal")
    static let rollingPeriod = CodingKeys(stringValue: "rollingPeriod")
    static let calendarPeriod = CodingKeys(stringValue: "calendarPeriod")
    static let userLabels = CodingKeys(stringValue: "userLabels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "serviceLevelIndicator",
      "goal",
      "rollingPeriod",
      "calendarPeriod",
      "userLabels",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.serviceLevelIndicator = try container.decodeIfPresent(
      ServiceLevelIndicator.self, forKey: .serviceLevelIndicator)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .goal) {
      self.goal = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .userLabels)
    {
      self.userLabels = value
    }

    var period: PeriodOneOf? = nil
    let periodCheckAndSet = {
      if period != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'period'"))
      }
      period = $0
    }
    if let rollingPeriod = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .rollingPeriod)
    {
      try periodCheckAndSet(.rollingPeriod(rollingPeriod))
    }
    if let calendarPeriod = try container.decodeIfPresent(
      GoogleType.CalendarPeriod.self, forKey: .calendarPeriod)
    {
      try periodCheckAndSet(.calendarPeriod(calendarPeriod))
    }
    self.period = period
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.serviceLevelIndicator, forKey: .serviceLevelIndicator)
    try container.encode(self.goal, forKey: .goal)
    try container.encode(self.userLabels, forKey: .userLabels)

    if let choice = self.period {
      switch choice {
      case .rollingPeriod(let value):
        try container.encode(value, forKey: .rollingPeriod)
      case .calendarPeriod(let value):
        try container.encode(value, forKey: .calendarPeriod)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// `ServiceLevelObjective.View` determines what form of
  /// `ServiceLevelObjective` is returned from `GetServiceLevelObjective`,
  /// `ListServiceLevelObjectives`, and `ListServiceLevelObjectiveVersions` RPCs.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum View: Codable, Equatable, Hashable, Sendable {
    /// Same as FULL.
    case unspecified
    /// For `ServiceLevelIndicator`s using `BasicSli` articulation, instead
    /// return the `ServiceLevelIndicator` with its mode of computation fully
    /// spelled out as a `RequestBasedSli`. For `ServiceLevelIndicator`s using
    /// `RequestBasedSli` or `WindowsBasedSli`, return the
    /// `ServiceLevelIndicator` as it was provided.
    case explicit
    /// Return the embedded `ServiceLevelIndicator` in the form in which it was
    /// defined. If it was defined using a `BasicSli`, return that `BasicSli`.
    case full
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .explicit: return 1
      case .full: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VIEW_UNSPECIFIED"
      case .explicit: return "EXPLICIT"
      case .full: return "FULL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:View/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VIEW_UNSPECIFIED": self = .unspecified
      case "FULL": self = .full
      case "EXPLICIT": self = .explicit
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:View/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .explicit
      case 2: self = .full
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VIEW_UNSPECIFIED")
      case .explicit: return try container.encode("EXPLICIT")
      case .full: return try container.encode("FULL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The time period over which the objective will be evaluated.
  public enum PeriodOneOf: Codable, Equatable, Sendable {
    /// A rolling time period, semantically "in the past `<rolling_period>`".
    /// Must be an integer multiple of 1 day no larger than 30 days.
    indirect case rollingPeriod(GoogleWKT.WKTDuration)
    /// A calendar period, semantically "since the start of the current
    /// `<calendar_period>`". At this time, only `DAY`, `WEEK`, `FORTNIGHT`, and
    /// `MONTH` are supported.
    case calendarPeriod(GoogleType.CalendarPeriod)
  }

  /// The type URL for `ServiceLevelObjective`: `"type.googleapis.com/google.monitoring.v3.ServiceLevelObjective"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.ServiceLevelObjective"
  }

  /// Initialize an instance of `ServiceLevelObjective` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.ServiceLevelObjective"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ServiceLevelObjective` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
