// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A `Snooze` will prevent any alerts from being opened, and close any that
/// are already open. The `Snooze` will work on alerts that match the
/// criteria defined in the `Snooze`. The `Snooze` will be active from
/// `interval.start_time` through `interval.end_time`.
public struct Snooze: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. The name of the `Snooze`. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/snoozes/[SNOOZE_ID]
  ///
  /// The ID of the `Snooze` will be generated by the system.
  public var name: Swift.String = Swift.String()

  /// Required. This defines the criteria for applying the `Snooze`. See
  /// `Criteria` for more information.
  public var criteria: Snooze.Criteria? = nil

  /// Required. The `Snooze` will be active from `interval.start_time` through
  /// `interval.end_time`.
  /// `interval.start_time` cannot be in the past. There is a 15 second clock
  /// skew to account for the time it takes for a request to reach the API from
  /// the UI.
  public var interval: TimeInterval? = nil

  /// Required. A display name for the `Snooze`. This can be, at most, 512
  /// unicode characters.
  public var displayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Snooze`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Snooze().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let criteria = CodingKeys(stringValue: "criteria")
    static let interval = CodingKeys(stringValue: "interval")
    static let displayName = CodingKeys(stringValue: "displayName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "criteria",
      "interval",
      "displayName",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.criteria = try container.decodeIfPresent(Snooze.Criteria.self, forKey: .criteria)
    self.interval = try container.decodeIfPresent(TimeInterval.self, forKey: .interval)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.criteria, forKey: .criteria)
    try container.encodeIfPresent(self.interval, forKey: .interval)
    try container.encode(self.displayName, forKey: .displayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Criteria specific to the `AlertPolicy`s that this `Snooze` applies to. The
  /// `Snooze` will suppress alerts that come from one of the `AlertPolicy`s
  /// whose names are supplied.
  public struct Criteria: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The specific `AlertPolicy` names for the alert that should be snoozed.
    /// The format is:
    ///
    ///     projects/[PROJECT_ID_OR_NUMBER]/alertPolicies/[POLICY_ID]
    ///
    /// There is a limit of 16 policies per snooze. This limit is checked during
    /// snooze creation.
    /// Exactly 1 alert policy is required if `filter` is specified at the same
    /// time.
    public var policies: [Swift.String] = []

    /// Optional. The filter string to match on Alert fields when silencing the
    /// alerts. It follows the standard https://google.aip.dev/160 syntax.
    /// A filter string used to apply the snooze to specific incidents
    /// that have matching filter values.
    /// Filters can be defined for snoozes that apply to one alerting
    /// policy.
    /// Filters must be a string formatted as one or more resource labels with
    /// specific label values. If multiple resource labels are used, then they
    /// must be connected with an AND operator. For example, the following filter
    /// applies the snooze to incidents that have an instance ID of
    /// `1234567890` and a zone of `us-central1-a`:
    ///
    ///     resource.labels.instance_id="1234567890" AND
    ///     resource.labels.zone="us-central1-a"
    public var filter: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Criteria`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Criteria().with { $0.policies = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let policies = CodingKeys(stringValue: "policies")
      static let filter = CodingKeys(stringValue: "filter")

      static let _knownKeys: Set<Swift.String> = [
        "policies",
        "filter",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .policies) {
        self.policies = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
        self.filter = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.policies, forKey: .policies)
      try container.encode(self.filter, forKey: .filter)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.Snooze.Criteria"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.Snooze"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
