// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A `TimeSeriesRatio` specifies two `TimeSeries` to use for computing the
/// `good_service / total_service` ratio. The specified `TimeSeries` must have
/// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
/// DELTA` or `MetricKind = CUMULATIVE`. The `TimeSeriesRatio` must specify
/// exactly two of good, bad, and total, and the relationship `good_service +
/// bad_service = total_service` will be assumed.
public struct TimeSeriesRatio: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying good service provided. Must have
  /// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
  /// DELTA` or `MetricKind = CUMULATIVE`.
  public var goodServiceFilter: Swift.String = Swift.String()

  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying bad service, either demanded service
  /// that was not provided or demanded service that was of inadequate quality.
  /// Must have `ValueType = DOUBLE` or `ValueType = INT64` and must have
  /// `MetricKind = DELTA` or `MetricKind = CUMULATIVE`.
  public var badServiceFilter: Swift.String = Swift.String()

  /// A [monitoring filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifying a `TimeSeries` quantifying total demanded service. Must have
  /// `ValueType = DOUBLE` or `ValueType = INT64` and must have `MetricKind =
  /// DELTA` or `MetricKind = CUMULATIVE`.
  public var totalServiceFilter: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimeSeriesRatio`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesRatio().with { $0.goodServiceFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let goodServiceFilter = CodingKeys(stringValue: "goodServiceFilter")
    static let badServiceFilter = CodingKeys(stringValue: "badServiceFilter")
    static let totalServiceFilter = CodingKeys(stringValue: "totalServiceFilter")

    static let _knownKeys: Set<Swift.String> = [
      "goodServiceFilter",
      "badServiceFilter",
      "totalServiceFilter",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .goodServiceFilter) {
      self.goodServiceFilter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .badServiceFilter) {
      self.badServiceFilter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .totalServiceFilter) {
      self.totalServiceFilter = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.goodServiceFilter, forKey: .goodServiceFilter)
    try container.encode(self.badServiceFilter, forKey: .badServiceFilter)
    try container.encode(self.totalServiceFilter, forKey: .totalServiceFilter)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeSeriesRatio"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
