// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleApi
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A collection of data points that describes the time-varying values
/// of a metric. A time series is identified by a combination of a
/// fully-specified monitored resource and a fully-specified metric.
/// This type is used for both listing and creating time series.
public struct TimeSeries: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The associated metric. A fully-specified metric used to identify the time
  /// series.
  public var metric: GoogleApi.Metric? = nil

  /// The associated monitored resource.  Custom metrics can use only certain
  /// monitored resource types in their time series data. For more information,
  /// see [Monitored resources for custom
  /// metrics](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#custom-metric-resources).
  public var resource: GoogleApi.MonitoredResource? = nil

  /// Output only. The associated monitored resource metadata. When reading a
  /// time series, this field will include metadata labels that are explicitly
  /// named in the reduction. When creating a time series, this field is ignored.
  public var metadata: GoogleApi.MonitoredResourceMetadata? = nil

  /// The metric kind of the time series. When listing time series, this metric
  /// kind might be different from the metric kind of the associated metric if
  /// this time series is an alignment or reduction of other time series.
  ///
  /// When creating a time series, this field is optional. If present, it must be
  /// the same as the metric kind of the associated metric. If the associated
  /// metric's descriptor must be auto-created, then this field specifies the
  /// metric kind of the new descriptor and must be either `GAUGE` (the default)
  /// or `CUMULATIVE`.
  public var metricKind: GoogleApi.MetricDescriptor.MetricKind = GoogleApi.MetricDescriptor
    .MetricKind()

  /// The value type of the time series. When listing time series, this value
  /// type might be different from the value type of the associated metric if
  /// this time series is an alignment or reduction of other time series.
  ///
  /// When creating a time series, this field is optional. If present, it must be
  /// the same as the type of the data in the `points` field.
  public var valueType: GoogleApi.MetricDescriptor.ValueType = GoogleApi.MetricDescriptor
    .ValueType()

  /// The data points of this time series. When listing time series, points are
  /// returned in reverse time order.
  ///
  /// When creating a time series, this field must contain exactly one point and
  /// the point's type must be the same as the value type of the associated
  /// metric. If the associated metric's descriptor must be auto-created, then
  /// the value type of the descriptor is determined by the point's type, which
  /// must be `BOOL`, `INT64`, `DOUBLE`, or `DISTRIBUTION`.
  public var points: [Point] = []

  /// The units in which the metric value is reported. It is only applicable
  /// if the `value_type` is `INT64`, `DOUBLE`, or `DISTRIBUTION`. The `unit`
  /// defines the representation of the stored metric values. This field can only
  /// be changed through CreateTimeSeries when it is empty.
  public var unit: Swift.String = Swift.String()

  /// Input only. A detailed description of the time series that will be
  /// associated with the
  /// [google.api.MetricDescriptor][google.api.MetricDescriptor] for the metric.
  /// Once set, this field cannot be changed through CreateTimeSeries.
  ///
  /// [google.api.MetricDescriptor]: https://www.google.com/search?q=Swift+google.api+GoogleApi.MetricDescriptor
  public var description: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimeSeries`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeries().with { $0.metric = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let metric = CodingKeys(stringValue: "metric")
    static let resource = CodingKeys(stringValue: "resource")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let metricKind = CodingKeys(stringValue: "metricKind")
    static let valueType = CodingKeys(stringValue: "valueType")
    static let points = CodingKeys(stringValue: "points")
    static let unit = CodingKeys(stringValue: "unit")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "metric",
      "resource",
      "metadata",
      "metricKind",
      "valueType",
      "points",
      "unit",
      "description",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.metric = try container.decodeIfPresent(GoogleApi.Metric.self, forKey: .metric)
    self.resource = try container.decodeIfPresent(
      GoogleApi.MonitoredResource.self, forKey: .resource)
    self.metadata = try container.decodeIfPresent(
      GoogleApi.MonitoredResourceMetadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(
      GoogleApi.MetricDescriptor.MetricKind.self, forKey: .metricKind)
    {
      self.metricKind = value
    }
    if let value = try container.decodeIfPresent(
      GoogleApi.MetricDescriptor.ValueType.self, forKey: .valueType)
    {
      self.valueType = value
    }
    if let value = try container.decodeIfPresent([Point].self, forKey: .points) {
      self.points = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .unit) {
      self.unit = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.metric, forKey: .metric)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.metricKind, forKey: .metricKind)
    try container.encode(self.valueType, forKey: .valueType)
    try container.encode(self.points, forKey: .points)
    try container.encode(self.unit, forKey: .unit)
    try container.encode(self.description, forKey: .description)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `TimeSeries`: `"type.googleapis.com/google.monitoring.v3.TimeSeries"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.TimeSeries"
  }

  /// Initialize an instance of `TimeSeries` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.TimeSeries"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `TimeSeries` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
