// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The message definition for updating a `Snooze`. The field, `snooze.name`
/// identifies the `Snooze` to be updated. The remainder of `snooze` gives the
/// content the `Snooze` in question will be assigned.
///
/// What fields can be updated depends on the start time and end time of the
/// `Snooze`.
///
///   * end time is in the past: These `Snooze`s are considered
///     read-only and cannot be updated.
///   * start time is in the past and end time is in the future: `display_name`
///     and `interval.end_time` can be updated.
///   * start time is in the future: `display_name`, `interval.start_time` and
///     `interval.end_time` can be updated.
public struct UpdateSnoozeRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The `Snooze` to update. Must have the name field present.
  public var snooze: Snooze? = nil

  /// Required. The fields to update.
  ///
  /// For each field listed in `update_mask`:
  ///
  ///   * If the `Snooze` object supplied in the `UpdateSnoozeRequest` has a
  ///     value for that field, the value of the field in the existing `Snooze`
  ///     will be set to the value of the field in the supplied `Snooze`.
  ///   * If the field does not have a value in the supplied `Snooze`, the field
  ///     in the existing `Snooze` is set to its default value.
  ///
  /// Fields not listed retain their existing value.
  ///
  /// The following are the field names that are accepted in `update_mask`:
  ///
  ///   * `display_name`
  ///   * `interval.start_time`
  ///   * `interval.end_time`
  ///
  /// That said, the start time and end time of the `Snooze` determines which
  /// fields can legally be updated. Before attempting an update, users should
  /// consult the documentation for `UpdateSnoozeRequest`, which talks about
  /// which fields can be updated.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateSnoozeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateSnoozeRequest().with { $0.snooze = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let snooze = CodingKeys(stringValue: "snooze")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "snooze",
      "updateMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.snooze = try container.decodeIfPresent(Snooze.self, forKey: .snooze)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.snooze, forKey: .snooze)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UpdateSnoozeRequest`: `"type.googleapis.com/google.monitoring.v3.UpdateSnoozeRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.UpdateSnoozeRequest"
  }

  /// Initialize an instance of `UpdateSnoozeRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UpdateSnoozeRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UpdateSnoozeRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
