// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The protocol for the `UpdateUptimeCheckConfig` request.
public struct UpdateUptimeCheckConfigRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If present, only the listed fields in the current Uptime check
  /// configuration are updated with values from the new configuration. If this
  /// field is empty, then the current configuration is completely replaced with
  /// the new configuration.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// Required. If an `updateMask` has been specified, this field gives
  /// the values for the set of fields mentioned in the `updateMask`. If an
  /// `updateMask` has not been given, this Uptime check configuration replaces
  /// the current configuration. If a field is mentioned in `updateMask` but
  /// the corresponding field is omitted in this partial Uptime check
  /// configuration, it has the effect of deleting/clearing the field from the
  /// configuration on the server.
  ///
  /// The following fields can be updated: `display_name`,
  /// `http_check`, `tcp_check`, `timeout`, `content_matchers`, and
  /// `selected_regions`.
  public var uptimeCheckConfig: UptimeCheckConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateUptimeCheckConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateUptimeCheckConfigRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let uptimeCheckConfig = CodingKeys(stringValue: "uptimeCheckConfig")

    static let _knownKeys: Set<Swift.String> = [
      "updateMask",
      "uptimeCheckConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    self.uptimeCheckConfig = try container.decodeIfPresent(
      UptimeCheckConfig.self, forKey: .uptimeCheckConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.uptimeCheckConfig, forKey: .uptimeCheckConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UpdateUptimeCheckConfigRequest`: `"type.googleapis.com/google.monitoring.v3.UpdateUptimeCheckConfigRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.UpdateUptimeCheckConfigRequest"
  }

  /// Initialize an instance of `UpdateUptimeCheckConfigRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UpdateUptimeCheckConfigRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UpdateUptimeCheckConfigRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
