// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// The UptimeCheckService API is used to manage (list, create, delete, edit)
/// Uptime check configurations in the Cloud Monitoring product. An Uptime
/// check is a piece of configuration that determines which resources and
/// services to monitor for availability. These configurations can also be
/// configured interactively by navigating to the [Cloud console]
/// (https://console.cloud.google.com), selecting the appropriate project,
/// clicking on "Monitoring" on the left-hand side to navigate to Cloud
/// Monitoring, and then clicking on "Uptime".
///
/// @Snippet(path: "UptimeCheckServiceQuickstart")
public final class UptimeCheckServiceClient: Clients.UptimeCheckServiceProtocol, Sendable {
  let inner: any Clients.UptimeCheckServiceStub

  /// Creates a new `UptimeCheckServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.UptimeCheckServiceStub = try Clients.UptimeCheckServiceTransport(options)
    inner = Clients.UptimeCheckServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.UptimeCheckServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the existing valid Uptime check configurations for the project
  /// (leaving out any invalid configurations).
  ///
  /// @Snippet(path: "UptimeCheckService_ListUptimeCheckConfigs")
  public func listUptimeCheckConfigs(
    request: ListUptimeCheckConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse {
    try await self.inner.listUptimeCheckConfigs(request: request, options: options)
  }

  /// Gets a single Uptime check configuration.
  ///
  /// @Snippet(path: "UptimeCheckService_GetUptimeCheckConfig")
  public func getUptimeCheckConfig(
    request: GetUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    try await self.inner.getUptimeCheckConfig(request: request, options: options)
  }

  /// Creates a new Uptime check configuration.
  ///
  /// @Snippet(path: "UptimeCheckService_CreateUptimeCheckConfig")
  public func createUptimeCheckConfig(
    request: CreateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    try await self.inner.createUptimeCheckConfig(request: request, options: options)
  }

  /// Updates an Uptime check configuration. You can either replace the entire
  /// configuration with a new one or replace only certain fields in the current
  /// configuration by specifying the fields to be updated via `updateMask`.
  /// Returns the updated configuration.
  ///
  /// @Snippet(path: "UptimeCheckService_UpdateUptimeCheckConfig")
  public func updateUptimeCheckConfig(
    request: UpdateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    try await self.inner.updateUptimeCheckConfig(request: request, options: options)
  }

  /// Deletes an Uptime check configuration. Note that this method will fail
  /// if the Uptime check configuration is referenced by an alert policy or
  /// other dependent configs that would be rendered invalid by the deletion.
  ///
  /// @Snippet(path: "UptimeCheckService_DeleteUptimeCheckConfig")
  public func deleteUptimeCheckConfig(
    request: DeleteUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteUptimeCheckConfig(request: request, options: options)
  }

  /// Returns the list of IP addresses that checkers run from.
  ///
  /// @Snippet(path: "UptimeCheckService_ListUptimeCheckIps")
  public func listUptimeCheckIps(
    request: ListUptimeCheckIpsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse {
    try await self.inner.listUptimeCheckIps(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `UptimeCheckServiceClient`.
  ///
  /// To mock `UptimeCheckServiceClient` change your functions to receive
  /// `some UptimeCheckServiceProtocol` or `any UptimeCheckServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol UptimeCheckServiceProtocol: Sendable {
    /// See `UptimeCheckServiceClient.listUptimeCheckConfigs`.
    func listUptimeCheckConfigs(
      request: ListUptimeCheckConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse

    /// See `UptimeCheckServiceClient.getUptimeCheckConfig`.
    func getUptimeCheckConfig(
      request: GetUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig

    /// See `UptimeCheckServiceClient.createUptimeCheckConfig`.
    func createUptimeCheckConfig(
      request: CreateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig

    /// See `UptimeCheckServiceClient.updateUptimeCheckConfig`.
    func updateUptimeCheckConfig(
      request: UpdateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig

    /// See `UptimeCheckServiceClient.deleteUptimeCheckConfig`.
    func deleteUptimeCheckConfig(
      request: DeleteUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `UptimeCheckServiceClient.listUptimeCheckIps`.
    func listUptimeCheckIps(
      request: ListUptimeCheckIpsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse
  }
}

// Default implementations
extension Clients.UptimeCheckServiceProtocol {
  public func listUptimeCheckConfigs(request: ListUptimeCheckConfigsRequest) async throws
    -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse
  {
    try await self.listUptimeCheckConfigs(request: request, options: .init())
  }

  public func listUptimeCheckConfigs(
    request: ListUptimeCheckConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUptimeCheckConfigsByItems(
    request: ListUptimeCheckConfigsRequest
  ) -> some AsyncSequence<UptimeCheckConfig, Swift.Error> & Sendable {
    self.listUptimeCheckConfigsByItems(request: request, options: .init())
  }

  /// Lists the existing valid Uptime check configurations for the project
  /// (leaving out any invalid configurations).
  ///
  /// @Snippet(path: "UptimeCheckService_ListUptimeCheckConfigs")
  public func listUptimeCheckConfigsByItems(
    request: ListUptimeCheckConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<UptimeCheckConfig, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListUptimeCheckConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUptimeCheckConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listUptimeCheckConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<UptimeCheckConfig, Swift.Error> & Sendable {
    let request = ListUptimeCheckConfigsRequest().with {
      $0.parent = parent
    }
    return self.listUptimeCheckConfigsByItems(request: request)
  }

  public func getUptimeCheckConfig(request: GetUptimeCheckConfigRequest) async throws
    -> GoogleCloudMonitoringV3.UptimeCheckConfig
  {
    try await self.getUptimeCheckConfig(request: request, options: .init())
  }

  public func getUptimeCheckConfig(
    request: GetUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getUptimeCheckConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    let request = GetUptimeCheckConfigRequest().with {
      $0.name = name
    }
    return try await self.getUptimeCheckConfig(request: request)
  }

  public func createUptimeCheckConfig(request: CreateUptimeCheckConfigRequest) async throws
    -> GoogleCloudMonitoringV3.UptimeCheckConfig
  {
    try await self.createUptimeCheckConfig(request: request, options: .init())
  }

  public func createUptimeCheckConfig(
    request: CreateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createUptimeCheckConfig(
    parent: Swift.String,
    uptimeCheckConfig: UptimeCheckConfig?,
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    let request = CreateUptimeCheckConfigRequest().with {
      $0.parent = parent
      $0.uptimeCheckConfig = uptimeCheckConfig
    }
    return try await self.createUptimeCheckConfig(request: request)
  }

  public func updateUptimeCheckConfig(request: UpdateUptimeCheckConfigRequest) async throws
    -> GoogleCloudMonitoringV3.UptimeCheckConfig
  {
    try await self.updateUptimeCheckConfig(request: request, options: .init())
  }

  public func updateUptimeCheckConfig(
    request: UpdateUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateUptimeCheckConfig(
    uptimeCheckConfig: UptimeCheckConfig?,
  ) async throws -> GoogleCloudMonitoringV3.UptimeCheckConfig {
    let request = UpdateUptimeCheckConfigRequest().with {
      $0.uptimeCheckConfig = uptimeCheckConfig
    }
    return try await self.updateUptimeCheckConfig(request: request)
  }

  public func deleteUptimeCheckConfig(request: DeleteUptimeCheckConfigRequest) async throws {
    try await self.deleteUptimeCheckConfig(request: request, options: .init())
  }

  public func deleteUptimeCheckConfig(
    request: DeleteUptimeCheckConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteUptimeCheckConfig(
    name: Swift.String,
  ) async throws {
    let request = DeleteUptimeCheckConfigRequest().with {
      $0.name = name
    }
    try await self.deleteUptimeCheckConfig(request: request)
  }

  public func listUptimeCheckIps(request: ListUptimeCheckIpsRequest) async throws
    -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse
  {
    try await self.listUptimeCheckIps(request: request, options: .init())
  }

  public func listUptimeCheckIps(
    request: ListUptimeCheckIpsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUptimeCheckIpsByItems(
    request: ListUptimeCheckIpsRequest
  ) -> some AsyncSequence<UptimeCheckIp, Swift.Error> & Sendable {
    self.listUptimeCheckIpsByItems(request: request, options: .init())
  }

  /// Returns the list of IP addresses that checkers run from.
  ///
  /// @Snippet(path: "UptimeCheckService_ListUptimeCheckIps")
  public func listUptimeCheckIpsByItems(
    request: ListUptimeCheckIpsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<UptimeCheckIp, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudMonitoringV3.ListUptimeCheckIpsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUptimeCheckIps(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }
}
