// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
public import GoogleApi
@_spi(GoogleCloudInternal) public import GoogleWKT

/// This message configures which resources and services to monitor for
/// availability.
public struct UptimeCheckConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. A unique resource name for this Uptime check configuration. The
  /// format is:
  ///
  ///      projects/[PROJECT_ID_OR_NUMBER]/uptimeCheckConfigs/[UPTIME_CHECK_ID]
  ///
  /// `[PROJECT_ID_OR_NUMBER]` is the Workspace host project associated with the
  /// Uptime check.
  ///
  /// This field should be omitted when creating the Uptime check configuration;
  /// on create, the resource name is assigned by the server and included in the
  /// response.
  public var name: Swift.String = Swift.String()

  /// A human-friendly name for the Uptime check configuration. The display name
  /// should be unique within a Cloud Monitoring Workspace in order to make it
  /// easier to identify; however, uniqueness is not enforced. Required.
  public var displayName: Swift.String = Swift.String()

  /// How often, in seconds, the Uptime check is performed.
  /// Currently, the only supported values are `60s` (1 minute), `300s`
  /// (5 minutes), `600s` (10 minutes), and `900s` (15 minutes). Optional,
  /// defaults to `60s`.
  public var period: GoogleWKT.WKTDuration? = nil

  /// The maximum amount of time to wait for the request to complete (must be
  /// between 1 and 60 seconds). Required.
  public var timeout: GoogleWKT.WKTDuration? = nil

  /// The content that is expected to appear in the data returned by the target
  /// server against which the check is run.  Currently, only the first entry
  /// in the `content_matchers` list is supported, and additional entries will
  /// be ignored. This field is optional and should only be specified if a
  /// content match is required as part of the/ Uptime check.
  public var contentMatchers: [UptimeCheckConfig.ContentMatcher] = []

  /// The type of checkers to use to execute the Uptime check.
  public var checkerType: UptimeCheckConfig.CheckerType = UptimeCheckConfig.CheckerType()

  /// The list of regions from which the check will be run.
  /// Some regions contain one location, and others contain more than one.
  /// If this field is specified, enough regions must be provided to include a
  /// minimum of 3 locations.  Not specifying this field will result in Uptime
  /// checks running from all available regions.
  public var selectedRegions: [UptimeCheckRegion] = []

  /// If this is `true`, then checks are made only from the 'internal_checkers'.
  /// If it is `false`, then checks are made only from the 'selected_regions'.
  /// It is an error to provide 'selected_regions' when is_internal is `true`,
  /// or to provide 'internal_checkers' when is_internal is `false`.
  @available(*, deprecated)
  public var isInternal: Swift.Bool = Swift.Bool()

  /// The internal checkers that this check will egress from. If `is_internal` is
  /// `true` and this list is empty, the check will egress from all the
  /// InternalCheckers configured for the project that owns this
  /// `UptimeCheckConfig`.
  @available(*, deprecated)
  public var internalCheckers: [InternalChecker] = []

  /// User-supplied key/value data to be used for organizing and
  /// identifying the `UptimeCheckConfig` objects.
  ///
  /// The field can contain up to 64 entries. Each key and value is limited to
  /// 63 Unicode characters or 128 bytes, whichever is smaller. Labels and
  /// values can contain only lowercase letters, numerals, underscores, and
  /// dashes. Keys must begin with a letter.
  public var userLabels: [Swift.String: Swift.String] = [:]

  /// The resource the check is checking. Required.
  public var resource: ResourceOneOf? = nil

  /// The type of Uptime check request.
  public var checkRequestType: CheckRequestTypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UptimeCheckConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UptimeCheckConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let monitoredResource = CodingKeys(stringValue: "monitoredResource")
    static let resourceGroup = CodingKeys(stringValue: "resourceGroup")
    static let syntheticMonitor = CodingKeys(stringValue: "syntheticMonitor")
    static let httpCheck = CodingKeys(stringValue: "httpCheck")
    static let tcpCheck = CodingKeys(stringValue: "tcpCheck")
    static let period = CodingKeys(stringValue: "period")
    static let timeout = CodingKeys(stringValue: "timeout")
    static let contentMatchers = CodingKeys(stringValue: "contentMatchers")
    static let checkerType = CodingKeys(stringValue: "checkerType")
    static let selectedRegions = CodingKeys(stringValue: "selectedRegions")
    static let isInternal = CodingKeys(stringValue: "isInternal")
    static let internalCheckers = CodingKeys(stringValue: "internalCheckers")
    static let userLabels = CodingKeys(stringValue: "userLabels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "monitoredResource",
      "resourceGroup",
      "syntheticMonitor",
      "httpCheck",
      "tcpCheck",
      "period",
      "timeout",
      "contentMatchers",
      "checkerType",
      "selectedRegions",
      "isInternal",
      "internalCheckers",
      "userLabels",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.period = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .period)
    self.timeout = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .timeout)
    if let value = try container.decodeIfPresent(
      [UptimeCheckConfig.ContentMatcher].self, forKey: .contentMatchers)
    {
      self.contentMatchers = value
    }
    if let value = try container.decodeIfPresent(
      UptimeCheckConfig.CheckerType.self, forKey: .checkerType)
    {
      self.checkerType = value
    }
    if let value = try container.decodeIfPresent([UptimeCheckRegion].self, forKey: .selectedRegions)
    {
      self.selectedRegions = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isInternal) {
      self.isInternal = value
    }
    if let value = try container.decodeIfPresent([InternalChecker].self, forKey: .internalCheckers)
    {
      self.internalCheckers = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .userLabels)
    {
      self.userLabels = value
    }

    var resource: ResourceOneOf? = nil
    let resourceCheckAndSet = {
      if resource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resource'"))
      }
      resource = $0
    }
    if let monitoredResource = try container.decodeIfPresent(
      GoogleApi.MonitoredResource.self, forKey: .monitoredResource)
    {
      try resourceCheckAndSet(.monitoredResource(monitoredResource))
    }
    if let resourceGroup = try container.decodeIfPresent(
      UptimeCheckConfig.ResourceGroup.self, forKey: .resourceGroup)
    {
      try resourceCheckAndSet(.resourceGroup(resourceGroup))
    }
    if let syntheticMonitor = try container.decodeIfPresent(
      SyntheticMonitorTarget.self, forKey: .syntheticMonitor)
    {
      try resourceCheckAndSet(.syntheticMonitor(syntheticMonitor))
    }
    self.resource = resource

    var checkRequestType: CheckRequestTypeOneOf? = nil
    let checkRequestTypeCheckAndSet = {
      if checkRequestType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'checkRequestType'"))
      }
      checkRequestType = $0
    }
    if let httpCheck = try container.decodeIfPresent(
      UptimeCheckConfig.HttpCheck.self, forKey: .httpCheck)
    {
      try checkRequestTypeCheckAndSet(.httpCheck(httpCheck))
    }
    if let tcpCheck = try container.decodeIfPresent(
      UptimeCheckConfig.TcpCheck.self, forKey: .tcpCheck)
    {
      try checkRequestTypeCheckAndSet(.tcpCheck(tcpCheck))
    }
    self.checkRequestType = checkRequestType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.period, forKey: .period)
    try container.encodeIfPresent(self.timeout, forKey: .timeout)
    try container.encode(self.contentMatchers, forKey: .contentMatchers)
    try container.encode(self.checkerType, forKey: .checkerType)
    try container.encode(self.selectedRegions, forKey: .selectedRegions)
    try container.encode(self.isInternal, forKey: .isInternal)
    try container.encode(self.internalCheckers, forKey: .internalCheckers)
    try container.encode(self.userLabels, forKey: .userLabels)

    if let choice = self.resource {
      switch choice {
      case .monitoredResource(let value):
        try container.encode(value, forKey: .monitoredResource)
      case .resourceGroup(let value):
        try container.encode(value, forKey: .resourceGroup)
      case .syntheticMonitor(let value):
        try container.encode(value, forKey: .syntheticMonitor)
      }
    }

    if let choice = self.checkRequestType {
      switch choice {
      case .httpCheck(let value):
        try container.encode(value, forKey: .httpCheck)
      case .tcpCheck(let value):
        try container.encode(value, forKey: .tcpCheck)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The resource submessage for group checks. It can be used instead of a
  /// monitored resource, when multiple resources are being monitored.
  public struct ResourceGroup: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The group of resources being monitored. Should be only the `[GROUP_ID]`,
    /// and not the full-path
    /// `projects/[PROJECT_ID_OR_NUMBER]/groups/[GROUP_ID]`.
    public var groupId: Swift.String = Swift.String()

    /// The resource type of the group members.
    public var resourceType: GroupResourceType = GroupResourceType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ResourceGroup`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceGroup().with { $0.groupId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let groupId = CodingKeys(stringValue: "groupId")
      static let resourceType = CodingKeys(stringValue: "resourceType")

      static let _knownKeys: Set<Swift.String> = [
        "groupId",
        "resourceType",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupId) {
        self.groupId = value
      }
      if let value = try container.decodeIfPresent(GroupResourceType.self, forKey: .resourceType) {
        self.resourceType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.groupId, forKey: .groupId)
      try container.encode(self.resourceType, forKey: .resourceType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `ResourceGroup`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ResourceGroup"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ResourceGroup"
    }

    /// Initialize an instance of `ResourceGroup` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ResourceGroup"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ResourceGroup` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information involved in sending ICMP pings alongside public HTTP/TCP
  /// checks. For HTTP, the pings are performed for each part of the redirect
  /// chain.
  public struct PingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Number of ICMP pings. A maximum of 3 ICMP pings is currently supported.
    public var pingsCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PingConfig().with { $0.pingsCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pingsCount = CodingKeys(stringValue: "pingsCount")

      static let _knownKeys: Set<Swift.String> = [
        "pingsCount"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pingsCount) {
        self.pingsCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.pingsCount, forKey: .pingsCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `PingConfig`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.PingConfig"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.PingConfig"
    }

    /// Initialize an instance of `PingConfig` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.PingConfig"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `PingConfig` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information involved in an HTTP/HTTPS Uptime check request.
  public struct HttpCheck: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The HTTP request method to use for the check. If set to
    /// `METHOD_UNSPECIFIED` then `request_method` defaults to `GET`.
    public var requestMethod: UptimeCheckConfig.HttpCheck.RequestMethod = UptimeCheckConfig
      .HttpCheck.RequestMethod()

    /// If `true`, use HTTPS instead of HTTP to run the check.
    public var useSsl: Swift.Bool = Swift.Bool()

    /// Optional (defaults to "/"). The path to the page against which to run
    /// the check. Will be combined with the `host` (specified within the
    /// `monitored_resource`) and `port` to construct the full URL. If the
    /// provided path does not begin with "/", a "/" will be prepended
    /// automatically.
    public var path: Swift.String = Swift.String()

    /// Optional (defaults to 80 when `use_ssl` is `false`, and 443 when
    /// `use_ssl` is `true`). The TCP port on the HTTP server against which to
    /// run the check. Will be combined with host (specified within the
    /// `monitored_resource`) and `path` to construct the full URL.
    public var port: Swift.Int32 = Swift.Int32()

    /// The authentication information. Optional when creating an HTTP check;
    /// defaults to empty.
    /// Do not set both `auth_method` and `auth_info`.
    public var authInfo: UptimeCheckConfig.HttpCheck.BasicAuthentication? = nil

    /// Boolean specifying whether to encrypt the header information.
    /// Encryption should be specified for any headers related to authentication
    /// that you do not wish to be seen when retrieving the configuration. The
    /// server will be responsible for encrypting the headers.
    /// On Get/List calls, if `mask_headers` is set to `true` then the headers
    /// will be obscured with `******.`
    public var maskHeaders: Swift.Bool = Swift.Bool()

    /// The list of headers to send as part of the Uptime check request.
    /// If two headers have the same key and different values, they should
    /// be entered as a single header, with the value being a comma-separated
    /// list of all the desired values as described at
    /// https://www.w3.org/Protocols/rfc2616/rfc2616.txt (page 31).
    /// Entering two separate headers with the same key in a Create call will
    /// cause the first to be overwritten by the second.
    /// The maximum number of headers allowed is 100.
    public var headers: [Swift.String: Swift.String] = [:]

    /// The content type header to use for the check. The following
    /// configurations result in errors:
    /// 1. Content type is specified in both the `headers` field and the
    /// `content_type` field.
    /// 2. Request method is `GET` and `content_type` is not `TYPE_UNSPECIFIED`
    /// 3. Request method is `POST` and `content_type` is `TYPE_UNSPECIFIED`.
    /// 4. Request method is `POST` and a "Content-Type" header is provided via
    /// `headers` field. The `content_type` field should be used instead.
    public var contentType: UptimeCheckConfig.HttpCheck.ContentType = UptimeCheckConfig.HttpCheck
      .ContentType()

    /// A user provided content type header to use for the check. The invalid
    /// configurations outlined in the `content_type` field apply to
    /// `custom_content_type`, as well as the following:
    /// 1. `content_type` is `URL_ENCODED` and `custom_content_type` is set.
    /// 2. `content_type` is `USER_PROVIDED` and `custom_content_type` is not
    /// set.
    public var customContentType: Swift.String = Swift.String()

    /// Boolean specifying whether to include SSL certificate validation as a
    /// part of the Uptime check. Only applies to checks where
    /// `monitored_resource` is set to `uptime_url`. If `use_ssl` is `false`,
    /// setting `validate_ssl` to `true` has no effect.
    public var validateSsl: Swift.Bool = Swift.Bool()

    /// The request body associated with the HTTP POST request. If `content_type`
    /// is `URL_ENCODED`, the body passed in must be URL-encoded. Users can
    /// provide a `Content-Length` header via the `headers` field or the API will
    /// do so. If the `request_method` is `GET` and `body` is not empty, the API
    /// will return an error. The maximum byte size is 1 megabyte.
    ///
    /// Note: If client libraries aren't used (which performs the conversion
    /// automatically) base64 encode your `body` data since the field is of
    /// `bytes` type.
    public var body: Foundation.Data = Foundation.Data()

    /// If present, the check will only pass if the HTTP response status code is
    /// in this set of status codes. If empty, the HTTP status code will only
    /// pass if the HTTP status code is 200-299.
    public var acceptedResponseStatusCodes: [UptimeCheckConfig.HttpCheck.ResponseStatusCode] = []

    /// Contains information needed to add pings to an HTTP check.
    public var pingConfig: UptimeCheckConfig.PingConfig? = nil

    /// This field is optional and should be set only by users interested in
    /// an authenticated uptime check.
    /// Do not set both `auth_method` and `auth_info`.
    public var authMethod: AuthMethodOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `HttpCheck`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HttpCheck().with { $0.requestMethod = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requestMethod = CodingKeys(stringValue: "requestMethod")
      static let useSsl = CodingKeys(stringValue: "useSsl")
      static let path = CodingKeys(stringValue: "path")
      static let port = CodingKeys(stringValue: "port")
      static let authInfo = CodingKeys(stringValue: "authInfo")
      static let maskHeaders = CodingKeys(stringValue: "maskHeaders")
      static let headers = CodingKeys(stringValue: "headers")
      static let contentType = CodingKeys(stringValue: "contentType")
      static let customContentType = CodingKeys(stringValue: "customContentType")
      static let validateSsl = CodingKeys(stringValue: "validateSsl")
      static let body = CodingKeys(stringValue: "body")
      static let acceptedResponseStatusCodes = CodingKeys(
        stringValue: "acceptedResponseStatusCodes")
      static let pingConfig = CodingKeys(stringValue: "pingConfig")
      static let serviceAgentAuthentication = CodingKeys(stringValue: "serviceAgentAuthentication")

      static let _knownKeys: Set<Swift.String> = [
        "requestMethod",
        "useSsl",
        "path",
        "port",
        "authInfo",
        "maskHeaders",
        "headers",
        "contentType",
        "customContentType",
        "validateSsl",
        "body",
        "acceptedResponseStatusCodes",
        "pingConfig",
        "serviceAgentAuthentication",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        UptimeCheckConfig.HttpCheck.RequestMethod.self, forKey: .requestMethod)
      {
        self.requestMethod = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useSsl) {
        self.useSsl = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
        self.port = value
      }
      self.authInfo = try container.decodeIfPresent(
        UptimeCheckConfig.HttpCheck.BasicAuthentication.self, forKey: .authInfo)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .maskHeaders) {
        self.maskHeaders = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .headers)
      {
        self.headers = value
      }
      if let value = try container.decodeIfPresent(
        UptimeCheckConfig.HttpCheck.ContentType.self, forKey: .contentType)
      {
        self.contentType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customContentType) {
        self.customContentType = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateSsl) {
        self.validateSsl = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .body) {
        self.body = value
      }
      if let value = try container.decodeIfPresent(
        [UptimeCheckConfig.HttpCheck.ResponseStatusCode].self, forKey: .acceptedResponseStatusCodes)
      {
        self.acceptedResponseStatusCodes = value
      }
      self.pingConfig = try container.decodeIfPresent(
        UptimeCheckConfig.PingConfig.self, forKey: .pingConfig)

      var authMethod: AuthMethodOneOf? = nil
      let authMethodCheckAndSet = {
        if authMethod != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'authMethod'"))
        }
        authMethod = $0
      }
      if let serviceAgentAuthentication = try container.decodeIfPresent(
        UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication.self,
        forKey: .serviceAgentAuthentication)
      {
        try authMethodCheckAndSet(.serviceAgentAuthentication(serviceAgentAuthentication))
      }
      self.authMethod = authMethod
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requestMethod, forKey: .requestMethod)
      try container.encode(self.useSsl, forKey: .useSsl)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.port, forKey: .port)
      try container.encodeIfPresent(self.authInfo, forKey: .authInfo)
      try container.encode(self.maskHeaders, forKey: .maskHeaders)
      try container.encode(self.headers, forKey: .headers)
      try container.encode(self.contentType, forKey: .contentType)
      try container.encode(self.customContentType, forKey: .customContentType)
      try container.encode(self.validateSsl, forKey: .validateSsl)
      try container.encode(self.body, forKey: .body)
      try container.encode(self.acceptedResponseStatusCodes, forKey: .acceptedResponseStatusCodes)
      try container.encodeIfPresent(self.pingConfig, forKey: .pingConfig)

      if let choice = self.authMethod {
        switch choice {
        case .serviceAgentAuthentication(let value):
          try container.encode(value, forKey: .serviceAgentAuthentication)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The authentication parameters to provide to the specified resource or
    /// URL that requires a username and password. Currently, only
    /// [Basic HTTP authentication](https://tools.ietf.org/html/rfc7617) is
    /// supported in Uptime checks.
    public struct BasicAuthentication: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The username to use when authenticating with the HTTP server.
      public var username: Swift.String = Swift.String()

      /// The password to use when authenticating with the HTTP server.
      public var password: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `BasicAuthentication`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BasicAuthentication().with { $0.username = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let username = CodingKeys(stringValue: "username")
        static let password = CodingKeys(stringValue: "password")

        static let _knownKeys: Set<Swift.String> = [
          "username",
          "password",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
          self.username = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
          self.password = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.username, forKey: .username)
        try container.encode(self.password, forKey: .password)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `BasicAuthentication`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.BasicAuthentication"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.BasicAuthentication"
      }

      /// Initialize an instance of `BasicAuthentication` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.BasicAuthentication"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `BasicAuthentication` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// A status to accept. Either a status code class like "2xx", or an integer
    /// status code like "200".
    public struct ResponseStatusCode: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Either a specific value or a class of status codes.
      public var statusCode: StatusCodeOneOf? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ResponseStatusCode`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ResponseStatusCode().with { $0.statusValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let statusValue = CodingKeys(stringValue: "statusValue")
        static let statusClass = CodingKeys(stringValue: "statusClass")

        static let _knownKeys: Set<Swift.String> = [
          "statusValue",
          "statusClass",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var statusCode: StatusCodeOneOf? = nil
        let statusCodeCheckAndSet = {
          if statusCode != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'statusCode'"))
          }
          statusCode = $0
        }
        if let statusValue = try container.decodeIfPresent(Swift.Int32.self, forKey: .statusValue) {
          try statusCodeCheckAndSet(.statusValue(statusValue))
        }
        if let statusClass = try container.decodeIfPresent(
          UptimeCheckConfig.HttpCheck.ResponseStatusCode.StatusClass.self, forKey: .statusClass)
        {
          try statusCodeCheckAndSet(.statusClass(statusClass))
        }
        self.statusCode = statusCode
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.statusCode {
          switch choice {
          case .statusValue(let value):
            try container.encode(value, forKey: .statusValue)
          case .statusClass(let value):
            try container.encode(value, forKey: .statusClass)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// An HTTP status code class.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum StatusClass: Codable, Equatable, Hashable, Sendable {
        /// Default value that matches no status codes.
        case unspecified
        /// The class of status codes between 100 and 199.
        case statusClass1Xx
        /// The class of status codes between 200 and 299.
        case statusClass2Xx
        /// The class of status codes between 300 and 399.
        case statusClass3Xx
        /// The class of status codes between 400 and 499.
        case statusClass4Xx
        /// The class of status codes between 500 and 599.
        case statusClass5Xx
        /// The class of all status codes.
        case any
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .statusClass1Xx: return 100
          case .statusClass2Xx: return 200
          case .statusClass3Xx: return 300
          case .statusClass4Xx: return 400
          case .statusClass5Xx: return 500
          case .any: return 1000
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "STATUS_CLASS_UNSPECIFIED"
          case .statusClass1Xx: return "STATUS_CLASS_1XX"
          case .statusClass2Xx: return "STATUS_CLASS_2XX"
          case .statusClass3Xx: return "STATUS_CLASS_3XX"
          case .statusClass4Xx: return "STATUS_CLASS_4XX"
          case .statusClass5Xx: return "STATUS_CLASS_5XX"
          case .any: return "STATUS_CLASS_ANY"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StatusClass/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "STATUS_CLASS_UNSPECIFIED": self = .unspecified
          case "STATUS_CLASS_1XX": self = .statusClass1Xx
          case "STATUS_CLASS_2XX": self = .statusClass2Xx
          case "STATUS_CLASS_3XX": self = .statusClass3Xx
          case "STATUS_CLASS_4XX": self = .statusClass4Xx
          case "STATUS_CLASS_5XX": self = .statusClass5Xx
          case "STATUS_CLASS_ANY": self = .any
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StatusClass/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 100: self = .statusClass1Xx
          case 200: self = .statusClass2Xx
          case 300: self = .statusClass3Xx
          case 400: self = .statusClass4Xx
          case 500: self = .statusClass5Xx
          case 1000: self = .any
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("STATUS_CLASS_UNSPECIFIED")
          case .statusClass1Xx: return try container.encode("STATUS_CLASS_1XX")
          case .statusClass2Xx: return try container.encode("STATUS_CLASS_2XX")
          case .statusClass3Xx: return try container.encode("STATUS_CLASS_3XX")
          case .statusClass4Xx: return try container.encode("STATUS_CLASS_4XX")
          case .statusClass5Xx: return try container.encode("STATUS_CLASS_5XX")
          case .any: return try container.encode("STATUS_CLASS_ANY")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// Either a specific value or a class of status codes.
      public enum StatusCodeOneOf: Codable, Equatable, Sendable {
        /// A status code to accept.
        case statusValue(Swift.Int32)
        /// A class of status codes to accept.
        case statusClass(UptimeCheckConfig.HttpCheck.ResponseStatusCode.StatusClass)
      }

      /// The type URL for `ResponseStatusCode`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ResponseStatusCode"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ResponseStatusCode"
      }

      /// Initialize an instance of `ResponseStatusCode` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ResponseStatusCode"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ResponseStatusCode` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Contains information needed for generating either an
    /// [OpenID Connect
    /// token](https://developers.google.com/identity/protocols/OpenIDConnect) or
    /// [OAuth token](https://developers.google.com/identity/protocols/oauth2).
    /// The token will be generated for the Monitoring service agent service
    /// account.
    public struct ServiceAgentAuthentication: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Type of authentication.
      public var type:
        UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication.ServiceAgentAuthenticationType =
          UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication.ServiceAgentAuthenticationType()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ServiceAgentAuthentication`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ServiceAgentAuthentication().with { $0.type = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let type = CodingKeys(stringValue: "type")

        static let _knownKeys: Set<Swift.String> = [
          "type"
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication.ServiceAgentAuthenticationType
            .self, forKey: .type)
        {
          self.type = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.type, forKey: .type)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Type of authentication.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum ServiceAgentAuthenticationType: Codable, Equatable, Hashable, Sendable {
        /// Default value, will result in OIDC Authentication.
        case unspecified
        /// OIDC Authentication
        case oidcToken
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .oidcToken: return 1
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "SERVICE_AGENT_AUTHENTICATION_TYPE_UNSPECIFIED"
          case .oidcToken: return "OIDC_TOKEN"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServiceAgentAuthenticationType/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "SERVICE_AGENT_AUTHENTICATION_TYPE_UNSPECIFIED": self = .unspecified
          case "OIDC_TOKEN": self = .oidcToken
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServiceAgentAuthenticationType/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .oidcToken
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified:
            return try container.encode("SERVICE_AGENT_AUTHENTICATION_TYPE_UNSPECIFIED")
          case .oidcToken: return try container.encode("OIDC_TOKEN")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// The type URL for `ServiceAgentAuthentication`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication"
      }

      /// Initialize an instance of `ServiceAgentAuthentication` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ServiceAgentAuthentication` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The HTTP request method options.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum RequestMethod: Codable, Equatable, Hashable, Sendable {
      /// No request method specified.
      case methodUnspecified
      /// GET request.
      case `get`
      /// POST request.
      case post
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .methodUnspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .methodUnspecified: return 0
        case .`get`: return 1
        case .post: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .methodUnspecified: return "METHOD_UNSPECIFIED"
        case .`get`: return "GET"
        case .post: return "POST"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RequestMethod/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "METHOD_UNSPECIFIED": self = .methodUnspecified
        case "GET": self = .`get`
        case "POST": self = .post
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RequestMethod/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .methodUnspecified
        case 1: self = .`get`
        case 2: self = .post
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .methodUnspecified: return try container.encode("METHOD_UNSPECIFIED")
        case .`get`: return try container.encode("GET")
        case .post: return try container.encode("POST")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Header options corresponding to the content type of a HTTP request body.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ContentType: Codable, Equatable, Hashable, Sendable {
      /// No content type specified.
      case typeUnspecified
      /// `body` is in URL-encoded form. Equivalent to setting the `Content-Type`
      /// to `application/x-www-form-urlencoded` in the HTTP request.
      case urlEncoded
      /// `body` is in `custom_content_type` form. Equivalent to setting the
      /// `Content-Type` to the contents of `custom_content_type` in the HTTP
      /// request.
      case userProvided
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .typeUnspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .typeUnspecified: return 0
        case .urlEncoded: return 1
        case .userProvided: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .typeUnspecified: return "TYPE_UNSPECIFIED"
        case .urlEncoded: return "URL_ENCODED"
        case .userProvided: return "USER_PROVIDED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContentType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .typeUnspecified
        case "URL_ENCODED": self = .urlEncoded
        case "USER_PROVIDED": self = .userProvided
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContentType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .typeUnspecified
        case 1: self = .urlEncoded
        case 2: self = .userProvided
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUnspecified: return try container.encode("TYPE_UNSPECIFIED")
        case .urlEncoded: return try container.encode("URL_ENCODED")
        case .userProvided: return try container.encode("USER_PROVIDED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// This field is optional and should be set only by users interested in
    /// an authenticated uptime check.
    /// Do not set both `auth_method` and `auth_info`.
    public enum AuthMethodOneOf: Codable, Equatable, Sendable {
      /// If specified, Uptime will generate and attach an OIDC JWT token for the
      /// Monitoring service agent service account as an `Authorization` header
      /// in the HTTP request when probing.
      indirect case serviceAgentAuthentication(
        UptimeCheckConfig.HttpCheck.ServiceAgentAuthentication)
    }

    /// The type URL for `HttpCheck`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck"
    }

    /// Initialize an instance of `HttpCheck` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.HttpCheck"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `HttpCheck` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information required for a TCP Uptime check request.
  public struct TcpCheck: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The TCP port on the server against which to run the check. Will be
    /// combined with host (specified within the `monitored_resource`) to
    /// construct the full URL. Required.
    public var port: Swift.Int32 = Swift.Int32()

    /// Contains information needed to add pings to a TCP check.
    public var pingConfig: UptimeCheckConfig.PingConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TcpCheck`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TcpCheck().with { $0.port = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let port = CodingKeys(stringValue: "port")
      static let pingConfig = CodingKeys(stringValue: "pingConfig")

      static let _knownKeys: Set<Swift.String> = [
        "port",
        "pingConfig",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
        self.port = value
      }
      self.pingConfig = try container.decodeIfPresent(
        UptimeCheckConfig.PingConfig.self, forKey: .pingConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.port, forKey: .port)
      try container.encodeIfPresent(self.pingConfig, forKey: .pingConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `TcpCheck`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.TcpCheck"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.TcpCheck"
    }

    /// Initialize an instance of `TcpCheck` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.TcpCheck"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `TcpCheck` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Optional. Used to perform content matching. This allows matching based on
  /// substrings and regular expressions, together with their negations. Only the
  /// first 4&nbsp;MB of an HTTP or HTTPS check's response (and the first
  /// 1&nbsp;MB of a TCP check's response) are examined for purposes of content
  /// matching.
  public struct ContentMatcher: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// String, regex or JSON content to match. Maximum 1024 bytes. An empty
    /// `content` string indicates no content matching is to be performed.
    public var content: Swift.String = Swift.String()

    /// The type of content matcher that will be applied to the server output,
    /// compared to the `content` string when the check is run.
    public var matcher: UptimeCheckConfig.ContentMatcher.ContentMatcherOption = UptimeCheckConfig
      .ContentMatcher.ContentMatcherOption()

    /// Certain `ContentMatcherOption` types require additional information.
    /// `MATCHES_JSON_PATH` or `NOT_MATCHES_JSON_PATH` require a
    /// `JsonPathMatcher`; not used for other options.
    public var additionalMatcherInfo: AdditionalMatcherInfoOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ContentMatcher`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ContentMatcher().with { $0.content = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let content = CodingKeys(stringValue: "content")
      static let matcher = CodingKeys(stringValue: "matcher")
      static let jsonPathMatcher = CodingKeys(stringValue: "jsonPathMatcher")

      static let _knownKeys: Set<Swift.String> = [
        "content",
        "matcher",
        "jsonPathMatcher",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
        self.content = value
      }
      if let value = try container.decodeIfPresent(
        UptimeCheckConfig.ContentMatcher.ContentMatcherOption.self, forKey: .matcher)
      {
        self.matcher = value
      }

      var additionalMatcherInfo: AdditionalMatcherInfoOneOf? = nil
      let additionalMatcherInfoCheckAndSet = {
        if additionalMatcherInfo != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'additionalMatcherInfo'"))
        }
        additionalMatcherInfo = $0
      }
      if let jsonPathMatcher = try container.decodeIfPresent(
        UptimeCheckConfig.ContentMatcher.JsonPathMatcher.self, forKey: .jsonPathMatcher)
      {
        try additionalMatcherInfoCheckAndSet(.jsonPathMatcher(jsonPathMatcher))
      }
      self.additionalMatcherInfo = additionalMatcherInfo
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.content, forKey: .content)
      try container.encode(self.matcher, forKey: .matcher)

      if let choice = self.additionalMatcherInfo {
        switch choice {
        case .jsonPathMatcher(let value):
          try container.encode(value, forKey: .jsonPathMatcher)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Information needed to perform a JSONPath content match.
    /// Used for `ContentMatcherOption::MATCHES_JSON_PATH` and
    /// `ContentMatcherOption::NOT_MATCHES_JSON_PATH`.
    public struct JsonPathMatcher: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// JSONPath within the response output pointing to the expected
      /// `ContentMatcher::content` to match against.
      public var jsonPath: Swift.String = Swift.String()

      /// The type of JSONPath match that will be applied to the JSON output
      /// (`ContentMatcher.content`)
      public var jsonMatcher:
        UptimeCheckConfig.ContentMatcher.JsonPathMatcher.JsonPathMatcherOption = UptimeCheckConfig
          .ContentMatcher.JsonPathMatcher.JsonPathMatcherOption()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `JsonPathMatcher`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = JsonPathMatcher().with { $0.jsonPath = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let jsonPath = CodingKeys(stringValue: "jsonPath")
        static let jsonMatcher = CodingKeys(stringValue: "jsonMatcher")

        static let _knownKeys: Set<Swift.String> = [
          "jsonPath",
          "jsonMatcher",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jsonPath) {
          self.jsonPath = value
        }
        if let value = try container.decodeIfPresent(
          UptimeCheckConfig.ContentMatcher.JsonPathMatcher.JsonPathMatcherOption.self,
          forKey: .jsonMatcher)
        {
          self.jsonMatcher = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.jsonPath, forKey: .jsonPath)
        try container.encode(self.jsonMatcher, forKey: .jsonMatcher)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Options to perform JSONPath content matching.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum JsonPathMatcherOption: Codable, Equatable, Hashable, Sendable {
        /// No JSONPath matcher type specified (not valid).
        case unspecified
        /// Selects 'exact string' matching. The match succeeds if the content at
        /// the `json_path` within the output is exactly the same as the
        /// `content` string.
        case exactMatch
        /// Selects regular-expression matching. The match succeeds if the
        /// content at the `json_path` within the output matches the regular
        /// expression specified in the `content` string.
        case regexMatch
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .exactMatch: return 1
          case .regexMatch: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "JSON_PATH_MATCHER_OPTION_UNSPECIFIED"
          case .exactMatch: return "EXACT_MATCH"
          case .regexMatch: return "REGEX_MATCH"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JsonPathMatcherOption/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "JSON_PATH_MATCHER_OPTION_UNSPECIFIED": self = .unspecified
          case "EXACT_MATCH": self = .exactMatch
          case "REGEX_MATCH": self = .regexMatch
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JsonPathMatcherOption/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .exactMatch
          case 2: self = .regexMatch
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("JSON_PATH_MATCHER_OPTION_UNSPECIFIED")
          case .exactMatch: return try container.encode("EXACT_MATCH")
          case .regexMatch: return try container.encode("REGEX_MATCH")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// The type URL for `JsonPathMatcher`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher.JsonPathMatcher"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher.JsonPathMatcher"
      }

      /// Initialize an instance of `JsonPathMatcher` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher.JsonPathMatcher"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `JsonPathMatcher` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Options to perform content matching.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ContentMatcherOption: Codable, Equatable, Hashable, Sendable {
      /// No content matcher type specified (maintained for backward
      /// compatibility, but deprecated for future use).
      /// Treated as `CONTAINS_STRING`.
      case unspecified
      /// Selects substring matching. The match succeeds if the output contains
      /// the `content` string.  This is the default value for checks without
      /// a `matcher` option, or where the value of `matcher` is
      /// `CONTENT_MATCHER_OPTION_UNSPECIFIED`.
      case containsString
      /// Selects negation of substring matching. The match succeeds if the
      /// output does _NOT_ contain the `content` string.
      case notContainsString
      /// Selects regular-expression matching. The match succeeds if the output
      /// matches the regular expression specified in the `content` string.
      /// Regex matching is only supported for HTTP/HTTPS checks.
      case matchesRegex
      /// Selects negation of regular-expression matching. The match succeeds if
      /// the output does _NOT_ match the regular expression specified in the
      /// `content` string. Regex matching is only supported for HTTP/HTTPS
      /// checks.
      case notMatchesRegex
      /// Selects JSONPath matching. See `JsonPathMatcher` for details on when
      /// the match succeeds. JSONPath matching is only supported for HTTP/HTTPS
      /// checks.
      case matchesJsonPath
      /// Selects JSONPath matching. See `JsonPathMatcher` for details on when
      /// the match succeeds. Succeeds when output does _NOT_ match as specified.
      /// JSONPath is only supported for HTTP/HTTPS checks.
      case notMatchesJsonPath
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .containsString: return 1
        case .notContainsString: return 2
        case .matchesRegex: return 3
        case .notMatchesRegex: return 4
        case .matchesJsonPath: return 5
        case .notMatchesJsonPath: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONTENT_MATCHER_OPTION_UNSPECIFIED"
        case .containsString: return "CONTAINS_STRING"
        case .notContainsString: return "NOT_CONTAINS_STRING"
        case .matchesRegex: return "MATCHES_REGEX"
        case .notMatchesRegex: return "NOT_MATCHES_REGEX"
        case .matchesJsonPath: return "MATCHES_JSON_PATH"
        case .notMatchesJsonPath: return "NOT_MATCHES_JSON_PATH"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContentMatcherOption/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONTENT_MATCHER_OPTION_UNSPECIFIED": self = .unspecified
        case "CONTAINS_STRING": self = .containsString
        case "NOT_CONTAINS_STRING": self = .notContainsString
        case "MATCHES_REGEX": self = .matchesRegex
        case "NOT_MATCHES_REGEX": self = .notMatchesRegex
        case "MATCHES_JSON_PATH": self = .matchesJsonPath
        case "NOT_MATCHES_JSON_PATH": self = .notMatchesJsonPath
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContentMatcherOption/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .containsString
        case 2: self = .notContainsString
        case 3: self = .matchesRegex
        case 4: self = .notMatchesRegex
        case 5: self = .matchesJsonPath
        case 6: self = .notMatchesJsonPath
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CONTENT_MATCHER_OPTION_UNSPECIFIED")
        case .containsString: return try container.encode("CONTAINS_STRING")
        case .notContainsString: return try container.encode("NOT_CONTAINS_STRING")
        case .matchesRegex: return try container.encode("MATCHES_REGEX")
        case .notMatchesRegex: return try container.encode("NOT_MATCHES_REGEX")
        case .matchesJsonPath: return try container.encode("MATCHES_JSON_PATH")
        case .notMatchesJsonPath: return try container.encode("NOT_MATCHES_JSON_PATH")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Certain `ContentMatcherOption` types require additional information.
    /// `MATCHES_JSON_PATH` or `NOT_MATCHES_JSON_PATH` require a
    /// `JsonPathMatcher`; not used for other options.
    public enum AdditionalMatcherInfoOneOf: Codable, Equatable, Sendable {
      /// Matcher information for `MATCHES_JSON_PATH` and `NOT_MATCHES_JSON_PATH`
      indirect case jsonPathMatcher(UptimeCheckConfig.ContentMatcher.JsonPathMatcher)
    }

    /// The type URL for `ContentMatcher`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher"
    }

    /// Initialize an instance of `ContentMatcher` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig.ContentMatcher"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ContentMatcher` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// What kind of checkers are available to be used by the check.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CheckerType: Codable, Equatable, Hashable, Sendable {
    /// The default checker type. Currently converted to `STATIC_IP_CHECKERS`
    /// on creation, the default conversion behavior may change in the future.
    case unspecified
    /// `STATIC_IP_CHECKERS` are used for uptime checks that perform egress
    /// across the public internet. `STATIC_IP_CHECKERS` use the static IP
    /// addresses returned by `ListUptimeCheckIps`.
    case staticIpCheckers
    /// `VPC_CHECKERS` are used for uptime checks that perform egress using
    /// Service Directory and private network access. When using `VPC_CHECKERS`,
    /// the monitored resource type must be `servicedirectory_service`.
    case vpcCheckers
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .staticIpCheckers: return 1
      case .vpcCheckers: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CHECKER_TYPE_UNSPECIFIED"
      case .staticIpCheckers: return "STATIC_IP_CHECKERS"
      case .vpcCheckers: return "VPC_CHECKERS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CheckerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CHECKER_TYPE_UNSPECIFIED": self = .unspecified
      case "STATIC_IP_CHECKERS": self = .staticIpCheckers
      case "VPC_CHECKERS": self = .vpcCheckers
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CheckerType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .staticIpCheckers
      case 3: self = .vpcCheckers
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CHECKER_TYPE_UNSPECIFIED")
      case .staticIpCheckers: return try container.encode("STATIC_IP_CHECKERS")
      case .vpcCheckers: return try container.encode("VPC_CHECKERS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The resource the check is checking. Required.
  public enum ResourceOneOf: Codable, Equatable, Sendable {
    /// The [monitored
    /// resource](https://cloud.google.com/monitoring/api/resources) associated
    /// with the configuration.
    /// The following monitored resource types are valid for this field:
    ///   `uptime_url`,
    ///   `gce_instance`,
    ///   `gae_app`,
    ///   `aws_ec2_instance`,
    ///   `aws_elb_load_balancer`
    ///   `k8s_service`
    ///   `servicedirectory_service`
    ///   `cloud_run_revision`
    indirect case monitoredResource(GoogleApi.MonitoredResource)
    /// The group resource associated with the configuration.
    indirect case resourceGroup(UptimeCheckConfig.ResourceGroup)
    /// Specifies a Synthetic Monitor to invoke.
    indirect case syntheticMonitor(SyntheticMonitorTarget)
  }

  /// The type of Uptime check request.
  public enum CheckRequestTypeOneOf: Codable, Equatable, Sendable {
    /// Contains information needed to make an HTTP or HTTPS check.
    indirect case httpCheck(UptimeCheckConfig.HttpCheck)
    /// Contains information needed to make a TCP check.
    indirect case tcpCheck(UptimeCheckConfig.TcpCheck)
  }

  /// The type URL for `UptimeCheckConfig`: `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.v3.UptimeCheckConfig"
  }

  /// Initialize an instance of `UptimeCheckConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.monitoring.v3.UptimeCheckConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UptimeCheckConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
