// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The regions from which an Uptime check can be run.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum UptimeCheckRegion: Codable, Equatable, Hashable, Sendable {
  /// Default value if no region is specified. Will result in Uptime checks
  /// running from all regions.
  case regionUnspecified
  /// Allows checks to run from locations within the United States of America.
  case usa
  /// Allows checks to run from locations within the continent of Europe.
  case europe
  /// Allows checks to run from locations within the continent of South
  /// America.
  case southAmerica
  /// Allows checks to run from locations within the Asia Pacific area (ex:
  /// Singapore).
  case asiaPacific
  /// Allows checks to run from locations within the western United States of
  /// America
  case usaOregon
  /// Allows checks to run from locations within the central United States of
  /// America
  case usaIowa
  /// Allows checks to run from locations within the eastern United States of
  /// America
  case usaVirginia
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .regionUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .regionUnspecified: return 0
    case .usa: return 1
    case .europe: return 2
    case .southAmerica: return 3
    case .asiaPacific: return 4
    case .usaOregon: return 5
    case .usaIowa: return 6
    case .usaVirginia: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .regionUnspecified: return "REGION_UNSPECIFIED"
    case .usa: return "USA"
    case .europe: return "EUROPE"
    case .southAmerica: return "SOUTH_AMERICA"
    case .asiaPacific: return "ASIA_PACIFIC"
    case .usaOregon: return "USA_OREGON"
    case .usaIowa: return "USA_IOWA"
    case .usaVirginia: return "USA_VIRGINIA"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UptimeCheckRegion/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "REGION_UNSPECIFIED": self = .regionUnspecified
    case "USA": self = .usa
    case "EUROPE": self = .europe
    case "SOUTH_AMERICA": self = .southAmerica
    case "ASIA_PACIFIC": self = .asiaPacific
    case "USA_OREGON": self = .usaOregon
    case "USA_IOWA": self = .usaIowa
    case "USA_VIRGINIA": self = .usaVirginia
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UptimeCheckRegion/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .regionUnspecified
    case 1: self = .usa
    case 2: self = .europe
    case 3: self = .southAmerica
    case 4: self = .asiaPacific
    case 5: self = .usaOregon
    case 6: self = .usaIowa
    case 7: self = .usaVirginia
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .regionUnspecified: return try container.encode("REGION_UNSPECIFIED")
    case .usa: return try container.encode("USA")
    case .europe: return try container.encode("EUROPE")
    case .southAmerica: return try container.encode("SOUTH_AMERICA")
    case .asiaPacific: return try container.encode("ASIA_PACIFIC")
    case .usaOregon: return try container.encode("USA_OREGON")
    case .usaIowa: return try container.encode("USA_IOWA")
    case .usaVirginia: return try container.encode("USA_VIRGINIA")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
